export interface Purchase {
  orderId?: string;
  copies: number;
  purchaseDate: string;
  fundAllocation?: string;
  licenseType?: string;
  unitPrice?: string;
}

export interface LibraryBorrower {
  id: string;
  name: string;
  role: "Student" | "Faculty" | "Research Scholar" | "Staff";
  avatarBg?: string;
  borrowDate: string;
  dueDate: string;
  progress: number;
}

export interface LibraryBook {
  id: string;
  title: string;
  publisher: string;
  copies: number;
  purchaseDate: string;
  status: "Active" | "Inactive";
  initials: string;
  cover: string;
  author: string;
  category: string;
  subCategory?: string;
  isbn: string;
  rating: number;
  description: string;
  format?: string;
  language?: string;
  sizeMB?: string;
  pages?: number;
  edition?: string;
  publicationYear?: string;
  purchases?: Purchase[];
  tags?: string[];
  departments?: string[];
  courses?: string[];
  borrowers?: LibraryBorrower[];
}

export const initialLibraryBooks: LibraryBook[] = [
  {
    id: "lib-1",
    title: "The Innocents Abroad",
    publisher: "PixelBooks",
    copies: 25,
    purchaseDate: "23 Mar 2026",
    status: "Active",
    initials: "TIA",
    cover: "linear-gradient(135deg, oklch(0.55 0.14 240), oklch(0.35 0.09 240))",
    author: "Mark Twain",
    category: "Travel & History",
    subCategory: "19th Century Travel Memoirs",
    isbn: "9780199540013",
    rating: 4.5,
    format: "EPUB",
    language: "English",
    sizeMB: "4.8 MB",
    pages: 496,
    edition: "Annotated Academic Edition",
    publicationYear: "1869 (Digital 2026)",
    description:
      "Mark Twain's classic travelogue detailing his journey through Europe and the Holy Land aboard the steamship Quaker City. Filled with humor, satire, and vivid cultural commentary.",
    tags: ["#Travelogue", "#AmericanLiterature", "#Satire", "#HistoricTravel", "#MarkTwain"],
    departments: ["Department of English", "Humanities & Cultural Studies", "History"],
    courses: ["B.A. English Literature", "M.A. Comparative Literature", "Foundation Humanities"],
    purchases: [
      {
        orderId: "LIB-PO-2026-0814",
        copies: 15,
        purchaseDate: "23 Mar 2026",
        fundAllocation: "Central Library Fund",
        licenseType: "Perpetual Multi-Seat",
        unitPrice: "₹450.00",
      },
      {
        orderId: "LIB-PO-2026-0120",
        copies: 10,
        purchaseDate: "15 Jan 2026",
        fundAllocation: "Humanities Grant",
        licenseType: "Perpetual Multi-Seat",
        unitPrice: "₹450.00",
      },
    ],
    borrowers: [
      {
        id: "bor-1",
        name: "Aarav Sharma",
        role: "Student",
        avatarBg: "linear-gradient(135deg, #0284c7, #0369a1)",
        borrowDate: "28 Sep 2026",
        dueDate: "12 Oct 2026",
        progress: 74,
      },
      {
        id: "bor-2",
        name: "Dr. Rachel Green",
        role: "Faculty",
        avatarBg: "linear-gradient(135deg, #4f46e5, #4338ca)",
        borrowDate: "22 Sep 2026",
        dueDate: "20 Oct 2026",
        progress: 92,
      },
      {
        id: "bor-3",
        name: "Pooja Hegde",
        role: "Student",
        avatarBg: "linear-gradient(135deg, #059669, #047857)",
        borrowDate: "01 Oct 2026",
        dueDate: "15 Oct 2026",
        progress: 35,
      },
    ],
  },
  {
    id: "lib-2",
    title: "Life on the Mississippi",
    publisher: "PixelBooks",
    copies: 500,
    purchaseDate: "08 Jan 2026",
    status: "Active",
    initials: "LOM",
    cover: "linear-gradient(135deg, oklch(0.5 0.13 30), oklch(0.32 0.08 30))",
    author: "Mark Twain",
    category: "Memoir",
    subCategory: "Autobiography & Americana",
    isbn: "9780199537549",
    rating: 4.8,
    format: "EPUB",
    language: "English",
    sizeMB: "5.2 MB",
    pages: 416,
    edition: "Critical Student Edition",
    publicationYear: "1883 (Digital 2026)",
    description:
      "A memoir by Mark Twain of his days as a steamboat pilot on the Mississippi River before the American Civil War, combining river history with vivid personal recollections.",
    tags: ["#Memoir", "#AmericanHistory", "#MississippiRiver", "#Autobiography"],
    departments: ["Department of English", "History & Archives"],
    courses: ["B.A. English", "M.A. History", "Interdisciplinary Studies"],
    purchases: [
      {
        orderId: "LIB-PO-2026-0004",
        copies: 500,
        purchaseDate: "08 Jan 2026",
        fundAllocation: "Campus-Wide Institutional License",
        licenseType: "Perpetual Site License",
        unitPrice: "₹120.00",
      },
    ],
    borrowers: [
      {
        id: "bor-4",
        name: "Siddharth Verma",
        role: "Student",
        avatarBg: "linear-gradient(135deg, #0d9488, #0f766e)",
        borrowDate: "30 Sep 2026",
        dueDate: "14 Oct 2026",
        progress: 48,
      },
      {
        id: "bor-5",
        name: "Kavya Menon",
        role: "Student",
        avatarBg: "linear-gradient(135deg, #7c3aed, #6d28d9)",
        borrowDate: "25 Sep 2026",
        dueDate: "09 Oct 2026",
        progress: 81,
      },
    ],
  },
  {
    id: "lib-3",
    title: "On Growth and Form",
    publisher: "PixelBooks",
    copies: 25,
    purchaseDate: "03 Dec 2025",
    status: "Active",
    initials: "OGF",
    cover: "linear-gradient(135deg, oklch(0.5 0.1 60), oklch(0.32 0.06 60))",
    author: "D'Arcy Wentworth Thompson",
    category: "Science & Biology",
    subCategory: "Morphogenesis & Mathematical Biology",
    isbn: "9780521437769",
    rating: 4.7,
    format: "PDF",
    language: "English",
    sizeMB: "14.2 MB",
    pages: 1116,
    edition: "Centenary Illustrated Edition",
    publicationYear: "1917 (Digital 2025)",
    description:
      "A mathematical beauty of biology, analyzing the way things grow and the physical forces shaping biological structures and organisms.",
    tags: ["#Biology", "#Biophysics", "#Morphogenesis", "#ClassicScience"],
    departments: ["Biological Sciences", "Department of Physics", "Mathematics"],
    courses: ["B.Sc Biology", "M.Sc Biophysics", "Mathematical Modeling"],
    purchases: [
      {
        orderId: "LIB-PO-2025-1192",
        copies: 25,
        purchaseDate: "03 Dec 2025",
        fundAllocation: "Science Consortium Grant",
        licenseType: "Perpetual Multi-Seat",
        unitPrice: "₹890.00",
      },
    ],
    borrowers: [
      {
        id: "bor-6",
        name: "Dr. Vikram Joshi",
        role: "Faculty",
        avatarBg: "linear-gradient(135deg, #059669, #047857)",
        borrowDate: "18 Sep 2026",
        dueDate: "16 Oct 2026",
        progress: 60,
      },
    ],
  },
  {
    id: "lib-4",
    title: "Of the Just Shaping of Letters",
    publisher: "PixelBooks",
    copies: 15,
    purchaseDate: "03 Dec 2025",
    status: "Active",
    initials: "OJS",
    cover: "linear-gradient(135deg, oklch(0.55 0.12 300), oklch(0.32 0.08 300))",
    author: "Albrecht Dürer",
    category: "Art & Typography",
    subCategory: "Geometric Typography & Renaissance Art",
    isbn: "9780486213064",
    rating: 4.2,
    format: "PDF",
    language: "English (Translated from German)",
    sizeMB: "8.5 MB",
    pages: 96,
    edition: "Facsimile Master Edition",
    publicationYear: "1525 (Digital 2025)",
    description:
      "A historic treatise on the geometric construction of Roman capitals and alphabets using compass and ruler principles.",
    tags: ["#Typography", "#Renaissance", "#AlbrechtDürer", "#DesignTheory"],
    departments: ["Fine Arts & Design", "Architecture", "Visual Communication"],
    courses: ["B.Des Graphic Design", "B.Arch Architecture", "Typography Workshop"],
    purchases: [
      {
        orderId: "LIB-PO-2025-1188",
        copies: 10,
        purchaseDate: "03 Dec 2025",
        fundAllocation: "Design Department Budget",
        licenseType: "Perpetual Multi-Seat",
        unitPrice: "₹520.00",
      },
      {
        orderId: "LIB-PO-2025-0980",
        copies: 5,
        purchaseDate: "10 Nov 2025",
        fundAllocation: "Art Faculty Fund",
        licenseType: "Perpetual Multi-Seat",
        unitPrice: "₹520.00",
      },
    ],
    borrowers: [
      {
        id: "bor-7",
        name: "Ananya Roy",
        role: "Student",
        avatarBg: "linear-gradient(135deg, #ec4899, #db2777)",
        borrowDate: "29 Sep 2026",
        dueDate: "13 Oct 2026",
        progress: 88,
      },
    ],
  },
  {
    id: "lib-5",
    title: "Knowledge for the Time",
    publisher: "PixelBooks",
    copies: 20,
    purchaseDate: "08 Dec 2025",
    status: "Active",
    initials: "KFT",
    cover: "linear-gradient(135deg, oklch(0.5 0.12 200), oklch(0.32 0.07 200))",
    author: "John Timbs",
    category: "Reference",
    subCategory: "Victorian Science & Curiosities",
    isbn: "9781019041857",
    rating: 4.0,
    format: "EPUB",
    language: "English",
    sizeMB: "3.9 MB",
    pages: 310,
    edition: "Archival Reference Edition",
    publicationYear: "1864 (Digital 2025)",
    description:
      "A manual of information on historical, scientific, and literary developments of the 19th century, exploring trivia, discoveries, and curiosities.",
    tags: ["#Reference", "#VictorianEra", "#ScienceHistory"],
    departments: ["General Reference", "History & Archives"],
    courses: ["Liberal Arts Core", "Research Methodology"],
    purchases: [
      {
        orderId: "LIB-PO-2025-1210",
        copies: 12,
        purchaseDate: "08 Dec 2025",
        fundAllocation: "Reference Section Allocation",
        licenseType: "Perpetual Multi-Seat",
        unitPrice: "₹380.00",
      },
      {
        orderId: "LIB-PO-2025-1044",
        copies: 8,
        purchaseDate: "20 Oct 2025",
        fundAllocation: "Central Reference Budget",
        licenseType: "Perpetual Multi-Seat",
        unitPrice: "₹380.00",
      },
    ],
    borrowers: [],
  },
  {
    id: "lib-6",
    title: "Gulliver's Travels Into Several Remote Regions of the World",
    publisher: "PixelBooks",
    copies: 30,
    purchaseDate: "03 Dec 2025",
    status: "Active",
    initials: "GTR",
    cover: "linear-gradient(135deg, oklch(0.45 0.09 145), oklch(0.28 0.06 145))",
    author: "Jonathan Swift",
    category: "Satire & Fiction",
    subCategory: "Satirical Allegory & Classics",
    isbn: "9780199535736",
    rating: 4.6,
    format: "EPUB",
    language: "English",
    sizeMB: "4.1 MB",
    pages: 368,
    edition: "Oxford World Classics Digital",
    publicationYear: "1726 (Digital 2025)",
    description:
      "A classic satirical novel in four parts, recounting Lemuel Gulliver's voyages to fantastical civilizations including Lilliput and Brobdingnag.",
    tags: ["#Classics", "#Satire", "#JonathanSwift", "#BritishLiterature"],
    departments: ["Department of English", "Humanities & Cultural Studies"],
    courses: ["B.A. English Literature", "M.A. English", "Foundations of Satire"],
    purchases: [
      {
        orderId: "LIB-PO-2025-1190",
        copies: 30,
        purchaseDate: "03 Dec 2025",
        fundAllocation: "Literature Department Budget",
        licenseType: "Perpetual Multi-Seat",
        unitPrice: "₹350.00",
      },
    ],
    borrowers: [
      {
        id: "bor-8",
        name: "Meera Nair",
        role: "Student",
        avatarBg: "linear-gradient(135deg, #0284c7, #0369a1)",
        borrowDate: "02 Oct 2026",
        dueDate: "16 Oct 2026",
        progress: 19,
      },
    ],
  },
  {
    id: "lib-7",
    title: "Common Sense",
    publisher: "PixelBooks",
    copies: 50,
    purchaseDate: "14 Nov 2025",
    status: "Active",
    initials: "CMS",
    cover: "linear-gradient(135deg, oklch(0.55 0.14 240), oklch(0.32 0.09 240))",
    author: "Thomas Paine",
    category: "Political Science",
    subCategory: "Political Philosophy & Pamphleteering",
    isbn: "9780486296029",
    rating: 4.5,
    format: "EPUB",
    language: "English",
    sizeMB: "1.8 MB",
    pages: 64,
    edition: "Historical Pamphlet Collection",
    publicationYear: "1776 (Digital 2025)",
    description:
      "A highly influential pamphlet advocating independence from Great Britain to the people in the Thirteen Colonies, framing revolution as moral necessity.",
    tags: ["#PoliticalTheory", "#ThomasPaine", "#AmericanRevolution"],
    departments: ["Political Science", "Law & Governance", "History"],
    courses: ["B.A. Political Science", "Constitutional Law", "Modern History"],
    purchases: [
      {
        orderId: "LIB-PO-2025-1120",
        copies: 50,
        purchaseDate: "14 Nov 2025",
        fundAllocation: "Social Sciences Grant",
        licenseType: "Perpetual Multi-Seat",
        unitPrice: "₹180.00",
      },
    ],
    borrowers: [
      {
        id: "bor-9",
        name: "Rohan Kapoor",
        role: "Research Scholar",
        avatarBg: "linear-gradient(135deg, #f59e0b, #d97706)",
        borrowDate: "27 Sep 2026",
        dueDate: "18 Oct 2026",
        progress: 95,
      },
    ],
  },
  {
    id: "lib-8",
    title: "A Tangled Tale",
    publisher: "PixelBooks",
    copies: 10,
    purchaseDate: "12 Oct 2025",
    status: "Inactive",
    initials: "ATT",
    cover: "linear-gradient(135deg, oklch(0.5 0.13 10), oklch(0.32 0.08 10))",
    author: "Lewis Carroll",
    category: "Mathematics & Humor",
    subCategory: "Recreational Math & Logic",
    isbn: "1646502779",
    rating: 4.3,
    format: "EPUB",
    language: "English",
    sizeMB: "3.2 MB",
    pages: 152,
    edition: "Illustrated Mathematical Edition",
    publicationYear: "1885 (Digital 2025)",
    description:
      "A series of humorous stories incorporating mathematical puzzles and knots to solve, written by the author of Alice in Wonderland.",
    tags: ["#Mathematics", "#Puzzles", "#Logic", "#LewisCarroll"],
    departments: ["Mathematics", "Computer Science"],
    courses: ["Discrete Mathematics", "Logic and Problem Solving"],
    purchases: [
      {
        orderId: "LIB-PO-2025-1010",
        copies: 10,
        purchaseDate: "12 Oct 2025",
        fundAllocation: "Math Club Endowment",
        licenseType: "Perpetual Multi-Seat",
        unitPrice: "₹290.00",
      },
    ],
    borrowers: [],
  },
  {
    id: "lib-9",
    title: "The Elements of Style",
    publisher: "PixelBooks",
    copies: 100,
    purchaseDate: "01 Oct 2025",
    status: "Active",
    initials: "STY",
    cover: "linear-gradient(135deg, oklch(0.55 0.12 300), oklch(0.32 0.08 300))",
    author: "William Strunk Jr.",
    category: "Writing Guide",
    subCategory: "Grammar, Composition & Style",
    isbn: "9780205309023",
    rating: 4.9,
    format: "EPUB",
    language: "English",
    sizeMB: "2.1 MB",
    pages: 105,
    edition: "Standard Reference Edition",
    publicationYear: "1918 (Digital 2025)",
    description:
      "The definitive manual of writing style in American English, including rules of composition, principles of clarity, and commonly misused expressions.",
    tags: ["#Writing", "#Grammar", "#Composition", "#StyleGuide"],
    departments: ["Department of English", "Journalism & Media", "Academic Writing Center"],
    courses: ["Academic Writing 101", "Business Communication", "Technical Writing"],
    purchases: [
      {
        orderId: "LIB-PO-2025-0955",
        copies: 100,
        purchaseDate: "01 Oct 2025",
        fundAllocation: "Campus Communications Fund",
        licenseType: "Perpetual Site License",
        unitPrice: "₹240.00",
      },
    ],
    borrowers: [
      {
        id: "bor-10",
        name: "Divya Nambiar",
        role: "Student",
        avatarBg: "linear-gradient(135deg, #0284c7, #0369a1)",
        borrowDate: "03 Oct 2026",
        dueDate: "17 Oct 2026",
        progress: 52,
      },
    ],
  },
  {
    id: "lib-10",
    title: "Meditations",
    publisher: "PixelBooks",
    copies: 75,
    purchaseDate: "15 Sep 2025",
    status: "Active",
    initials: "MED",
    cover: "linear-gradient(135deg, oklch(0.45 0.09 145), oklch(0.28 0.06 145))",
    author: "Marcus Aurelius",
    category: "Philosophy",
    subCategory: "Stoicism & Ancient Philosophy",
    isbn: "9780140449334",
    rating: 4.9,
    format: "EPUB",
    language: "English (Translated from Greek)",
    sizeMB: "3.7 MB",
    pages: 304,
    edition: "Penguin Classics Translation",
    publicationYear: "180 AD (Digital 2025)",
    description:
      "A series of personal writings by the Roman Emperor Marcus Aurelius, recording his private notes to himself and ideas on Stoic philosophy and governance.",
    tags: ["#Philosophy", "#Stoicism", "#MarcusAurelius", "#AncientRome", "#Ethics"],
    departments: ["Philosophy", "Humanities & Ethics", "School of Management"],
    courses: ["Introduction to Ethics", "Ancient Philosophy", "Leadership & Values"],
    purchases: [
      {
        orderId: "LIB-PO-2025-0899",
        copies: 45,
        purchaseDate: "15 Sep 2025",
        fundAllocation: "Philosophy Department Grant",
        licenseType: "Perpetual Multi-Seat",
        unitPrice: "₹399.00",
      },
      {
        orderId: "LIB-PO-2025-0720",
        copies: 30,
        purchaseDate: "01 Aug 2025",
        fundAllocation: "Central Library Fund",
        licenseType: "Perpetual Multi-Seat",
        unitPrice: "₹399.00",
      },
    ],
    borrowers: [
      {
        id: "bor-11",
        name: "Arjun Sen",
        role: "Student",
        avatarBg: "linear-gradient(135deg, #059669, #047857)",
        borrowDate: "26 Sep 2026",
        dueDate: "10 Oct 2026",
        progress: 89,
      },
    ],
  },
  {
    id: "lib-11",
    title: "The Republic",
    publisher: "PixelBooks",
    copies: 35,
    purchaseDate: "10 Aug 2025",
    status: "Inactive",
    initials: "REP",
    cover: "linear-gradient(135deg, oklch(0.5 0.1 60), oklch(0.32 0.06 60))",
    author: "Plato",
    category: "Philosophy",
    subCategory: "Political Philosophy & Dialectics",
    isbn: "9780872201361",
    rating: 4.8,
    format: "EPUB",
    language: "English",
    sizeMB: "4.5 MB",
    pages: 416,
    edition: "Hackett Classics Edition",
    publicationYear: "375 BC (Digital 2025)",
    description:
      "A Socratic dialogue concerning justice, the order and character of the just city-state, and the nature of the philosopher king.",
    tags: ["#Plato", "#Philosophy", "#Justice", "#PoliticalPhilosophy"],
    departments: ["Philosophy", "Political Science"],
    courses: ["Classical Political Thought", "Platonic Dialogues"],
    purchases: [
      {
        orderId: "LIB-PO-2025-0760",
        copies: 35,
        purchaseDate: "10 Aug 2025",
        fundAllocation: "Philosophy Department Budget",
        licenseType: "Perpetual Multi-Seat",
        unitPrice: "₹420.00",
      },
    ],
    borrowers: [],
  },
  {
    id: "lib-12",
    title: "A Brief History of Time",
    publisher: "PixelBooks",
    copies: 60,
    purchaseDate: "04 Aug 2025",
    status: "Active",
    initials: "BHT",
    cover: "linear-gradient(135deg, oklch(0.5 0.12 200), oklch(0.32 0.07 200))",
    author: "Stephen Hawking",
    category: "Cosmology",
    subCategory: "Astrophysics & Theoretical Physics",
    isbn: "9780553380163",
    rating: 4.7,
    format: "EPUB",
    language: "English",
    sizeMB: "6.8 MB",
    pages: 256,
    edition: "Illustrated Science Classic",
    publicationYear: "1988 (Digital 2025)",
    description:
      "A landmark popular-science book on cosmology, explaining black holes, the Big Bang, general relativity, and quantum mechanics to general readers.",
    tags: ["#Cosmology", "#Physics", "#StephenHawking", "#SpaceScience"],
    departments: ["Department of Physics", "Astronomy & Astrophysics", "General Science"],
    courses: ["B.Sc Physics", "Introduction to Cosmology", "M.Sc Astrophysics"],
    purchases: [
      {
        orderId: "LIB-PO-2025-0740",
        copies: 30,
        purchaseDate: "04 Aug 2025",
        fundAllocation: "Physics Dept Special Grant",
        licenseType: "Perpetual Multi-Seat",
        unitPrice: "₹550.00",
      },
      {
        orderId: "LIB-PO-2025-0680",
        copies: 20,
        purchaseDate: "15 Jul 2025",
        fundAllocation: "Central Science Budget",
        licenseType: "Perpetual Multi-Seat",
        unitPrice: "₹550.00",
      },
      {
        orderId: "LIB-PO-2025-0550",
        copies: 10,
        purchaseDate: "01 Jun 2025",
        fundAllocation: "Library Innovation Fund",
        licenseType: "Perpetual Multi-Seat",
        unitPrice: "₹550.00",
      },
    ],
    borrowers: [
      {
        id: "bor-12",
        name: "Sneha Mukherjee",
        role: "Student",
        avatarBg: "linear-gradient(135deg, #0284c7, #0369a1)",
        borrowDate: "01 Oct 2026",
        dueDate: "15 Oct 2026",
        progress: 63,
      },
    ],
  },
  {
    id: "lib-13",
    title: "The Art of War",
    publisher: "PixelBooks",
    copies: 40,
    purchaseDate: "22 Jul 2025",
    status: "Active",
    initials: "WAR",
    cover: "linear-gradient(135deg, oklch(0.5 0.13 10), oklch(0.32 0.08 10))",
    author: "Sun Tzu",
    category: "Military Strategy",
    subCategory: "Strategic Thinking & Conflict Management",
    isbn: "9781590302255",
    rating: 4.6,
    format: "EPUB",
    language: "English (Translated from Chinese)",
    sizeMB: "2.4 MB",
    pages: 176,
    edition: "Deluxe Commentary Edition",
    publicationYear: "5th Century BC (Digital 2025)",
    description:
      "An ancient Chinese military treatise attributed to Sun Tzu, detailing strategies for warfare, negotiation, psychological discipline, and conflict management.",
    tags: ["#Strategy", "#MilitaryHistory", "#SunTzu", "#Leadership"],
    departments: ["School of Business", "Defense Studies", "Political Science"],
    courses: ["M.B.A Strategic Management", "Negotiation Dynamics", "Geopolitics"],
    purchases: [
      {
        orderId: "LIB-PO-2025-0705",
        copies: 40,
        purchaseDate: "22 Jul 2025",
        fundAllocation: "Management Studies Budget",
        licenseType: "Perpetual Multi-Seat",
        unitPrice: "₹310.00",
      },
    ],
    borrowers: [
      {
        id: "bor-13",
        name: "Rahul Deshmukh",
        role: "Student",
        avatarBg: "linear-gradient(135deg, #059669, #047857)",
        borrowDate: "25 Sep 2026",
        dueDate: "09 Oct 2026",
        progress: 77,
      },
    ],
  },
  {
    id: "lib-14",
    title: "Pride and Prejudice",
    publisher: "PixelBooks",
    copies: 20,
    purchaseDate: "11 Jun 2025",
    status: "Inactive",
    initials: "PAP",
    cover: "linear-gradient(135deg, oklch(0.55 0.12 300), oklch(0.32 0.08 300))",
    author: "Jane Austen",
    category: "Romance & Fiction",
    subCategory: "Regency Romance & Novel of Manners",
    isbn: "9780141439518",
    rating: 4.8,
    format: "EPUB",
    language: "English",
    sizeMB: "3.8 MB",
    pages: 448,
    edition: "Penguin Classics Annotated",
    publicationYear: "1813 (Digital 2025)",
    description:
      "A romantic novel of manners following the character development of Elizabeth Bennet as she navigates societal expectations and Mr. Darcy.",
    tags: ["#JaneAusten", "#BritishClassics", "#Regency", "#Fiction"],
    departments: ["Department of English", "Gender Studies"],
    courses: ["B.A. English", "19th Century British Novel"],
    purchases: [
      {
        orderId: "LIB-PO-2025-0580",
        copies: 20,
        purchaseDate: "11 Jun 2025",
        fundAllocation: "Literature Dept Fund",
        licenseType: "Perpetual Multi-Seat",
        unitPrice: "₹280.00",
      },
    ],
    borrowers: [],
  },
  {
    id: "lib-15",
    title: "Frankenstein",
    publisher: "PixelBooks",
    copies: 35,
    purchaseDate: "30 May 2025",
    status: "Active",
    initials: "FRK",
    cover: "linear-gradient(135deg, oklch(0.55 0.14 240), oklch(0.35 0.09 240))",
    author: "Mary Shelley",
    category: "Gothic Horror",
    subCategory: "Early Science Fiction & Romanticism",
    isbn: "9780486282114",
    rating: 4.5,
    format: "EPUB",
    language: "English",
    sizeMB: "3.5 MB",
    pages: 280,
    edition: "1818 Text Critical Edition",
    publicationYear: "1818 (Digital 2025)",
    description:
      "The story of Victor Frankenstein, a young scientist who creates a sapient creature in an unorthodox scientific experiment with devastating consequences.",
    tags: ["#GothicHorror", "#ScienceFiction", "#MaryShelley", "#Romanticism"],
    departments: ["Department of English", "Bioethics"],
    courses: ["Gothic Literature", "Ethics in Science and Technology"],
    purchases: [
      {
        orderId: "LIB-PO-2025-0540",
        copies: 35,
        purchaseDate: "30 May 2025",
        fundAllocation: "Humanities Library Budget",
        licenseType: "Perpetual Multi-Seat",
        unitPrice: "₹320.00",
      },
    ],
    borrowers: [
      {
        id: "bor-14",
        name: "Harish Kumar",
        role: "Student",
        avatarBg: "linear-gradient(135deg, #0284c7, #0369a1)",
        borrowDate: "03 Oct 2026",
        dueDate: "17 Oct 2026",
        progress: 42,
      },
    ],
  },
  {
    id: "lib-16",
    title: "Walden",
    publisher: "PixelBooks",
    copies: 18,
    purchaseDate: "18 May 2025",
    status: "Inactive",
    initials: "WAL",
    cover: "linear-gradient(135deg, oklch(0.5 0.1 60), oklch(0.32 0.06 60))",
    author: "Henry David Thoreau",
    category: "Philosophy & Nature",
    subCategory: "Transcendentalism & Environmentalism",
    isbn: "9780486284958",
    rating: 4.4,
    format: "EPUB",
    language: "English",
    sizeMB: "3.1 MB",
    pages: 352,
    edition: "Transcendentalism Core Text",
    publicationYear: "1854 (Digital 2025)",
    description:
      "A reflection upon simple living in natural surroundings, detailing Thoreau's experiences over two years in a cabin near Walden Pond.",
    tags: ["#Transcendentalism", "#NatureWriting", "#Thoreau", "#Simplicity"],
    departments: ["Environmental Studies", "Philosophy", "English"],
    courses: ["Environmental Literature", "American Transcendentalism"],
    purchases: [
      {
        orderId: "LIB-PO-2025-0490",
        copies: 18,
        purchaseDate: "18 May 2025",
        fundAllocation: "Eco-Studies Grant",
        licenseType: "Perpetual Multi-Seat",
        unitPrice: "₹290.00",
      },
    ],
    borrowers: [],
  },
  {
    id: "lib-17",
    title: "The Wealth of Nations",
    publisher: "PixelBooks",
    copies: 50,
    purchaseDate: "02 May 2025",
    status: "Active",
    initials: "WON",
    cover: "linear-gradient(135deg, oklch(0.45 0.09 145), oklch(0.28 0.06 145))",
    author: "Adam Smith",
    category: "Economics",
    subCategory: "Classical Economics & Political Economy",
    isbn: "9780199535927",
    rating: 4.6,
    format: "EPUB",
    language: "English",
    sizeMB: "7.9 MB",
    pages: 960,
    edition: "Complete 2-Volume Edition",
    publicationYear: "1776 (Digital 2025)",
    description:
      "The magnum opus of the Scottish economist, discussing the economic and social mechanisms of the Industrial Revolution, the division of labor, and free markets.",
    tags: ["#Economics", "#AdamSmith", "#FreeMarket", "#PoliticalEconomy"],
    departments: ["Department of Economics", "School of Business", "Commerce"],
    courses: ["B.A. Economics", "M.A. Economics", "M.B.A Microeconomics"],
    purchases: [
      {
        orderId: "LIB-PO-2025-0440",
        copies: 50,
        purchaseDate: "02 May 2025",
        fundAllocation: "Economics Dept Endowment",
        licenseType: "Perpetual Multi-Seat",
        unitPrice: "₹620.00",
      },
    ],
    borrowers: [
      {
        id: "bor-15",
        name: "Dr. Sunita Rao",
        role: "Faculty",
        avatarBg: "linear-gradient(135deg, #4f46e5, #4338ca)",
        borrowDate: "20 Sep 2026",
        dueDate: "18 Oct 2026",
        progress: 85,
      },
    ],
  },
  {
    id: "lib-18",
    title: "Great Expectations",
    publisher: "PixelBooks",
    copies: 25,
    purchaseDate: "14 Apr 2025",
    status: "Inactive",
    initials: "GEX",
    cover: "linear-gradient(135deg, oklch(0.5 0.13 10), oklch(0.32 0.08 10))",
    author: "Charles Dickens",
    category: "Victorian Fiction",
    subCategory: "Bildungsroman & Social Satire",
    isbn: "9780141439563",
    rating: 4.5,
    format: "EPUB",
    language: "English",
    sizeMB: "4.7 MB",
    pages: 544,
    edition: "Penguin Classics Illustrated",
    publicationYear: "1861 (Digital 2025)",
    description:
      "The education and growth of an orphan nicknamed Pip, tracking his moral and social development in Victorian England.",
    tags: ["#CharlesDickens", "#VictorianNovel", "#Classics"],
    departments: ["Department of English", "History"],
    courses: ["B.A. English", "Victorian Literature"],
    purchases: [
      {
        orderId: "LIB-PO-2025-0370",
        copies: 25,
        purchaseDate: "14 Apr 2025",
        fundAllocation: "Literature Dept Fund",
        licenseType: "Perpetual Multi-Seat",
        unitPrice: "₹340.00",
      },
    ],
    borrowers: [],
  },
];

export function getLibraryBook(id: string): LibraryBook | undefined {
  return initialLibraryBooks.find((b) => b.id === id);
}
