export interface PublisherAuthorBook {
  id: string;
  title: string;
  category: string;
  isbn: string;
  author: string;
  publisher: string;
  dop: string;
  language: string;
  price: string;
  status: "Published" | "Draft" | "Archived";
  initials: string;
  coverGradient: string;
}

export const BOOKS_BY_ACCOUNT: Record<string, PublisherAuthorBook[]> = {
  // Werley Nortreus (Author - 6 titles)
  "pa-1": [
    {
      id: "b-wn-1",
      title: "The Art of Creative Writing",
      category: "Arts & Humanities",
      isbn: "978-1-4028-9457-7",
      author: "Werley Nortreus",
      publisher: "Beacon Publishing",
      dop: "18 May 2025",
      language: "English",
      price: "₹620.00",
      status: "Published",
      initials: "AC",
      coverGradient: "linear-gradient(135deg, #be185d 0%, #f43f5e 100%)",
    },
    {
      id: "b-wn-2",
      title: "Voices of Modern Poetry",
      category: "Poetry & Anthologies",
      isbn: "978-0-307-27767-1",
      author: "Werley Nortreus",
      publisher: "Horizon Press",
      dop: "22 Jun 2025",
      language: "English",
      price: "₹299.00",
      status: "Published",
      initials: "VP",
      coverGradient: "linear-gradient(135deg, #6b21a8 0%, #a855f7 100%)",
    },
    {
      id: "b-wn-3",
      title: "Chronicles of Ancient Empires",
      category: "History & Heritage",
      isbn: "978-0-19-856453-9",
      author: "Werley Nortreus",
      publisher: "Apex Lit House",
      dop: "02 Aug 2025",
      language: "English",
      price: "₹750.00",
      status: "Published",
      initials: "CA",
      coverGradient: "linear-gradient(135deg, #c2410c 0%, #f97316 100%)",
    },
    {
      id: "b-wn-4",
      title: "Contemporary Short Stories",
      category: "General & Literary Fiction",
      isbn: "978-0-14-044913-6",
      author: "Werley Nortreus",
      publisher: "OBook Publication",
      dop: "19 Sep 2025",
      language: "English",
      price: "₹340.00",
      status: "Published",
      initials: "CS",
      coverGradient: "linear-gradient(135deg, #0369a1 0%, #0ea5e9 100%)",
    },
    {
      id: "b-wn-5",
      title: "Selected Essays & Reflections",
      category: "Philosophy & Essays",
      isbn: "978-0-393-02046-5",
      author: "Werley Nortreus",
      publisher: "QA-TBH Publishers",
      dop: "05 Nov 2025",
      language: "English",
      price: "₹480.00",
      status: "Published",
      initials: "SE",
      coverGradient: "linear-gradient(135deg, #991b1b 0%, #ef4444 100%)",
    },
    {
      id: "b-wn-6",
      title: "Global Cultural Studies",
      category: "Social Sciences",
      isbn: "978-0-415-18116-7",
      author: "Werley Nortreus",
      publisher: "Beacon Publishing",
      dop: "10 Mar 2026",
      language: "English",
      price: "₹690.00",
      status: "Published",
      initials: "GC",
      coverGradient: "linear-gradient(135deg, #581c87 0%, #9333ea 100%)",
    },
  ],

  // QA-TBH Publishers (Publisher - 11 titles)
  "pa-4": [
    {
      id: "b-tbh-1",
      title: "Elsaunderajoseph",
      category: "General & Literary Fiction",
      isbn: "978-0-12-345678-9",
      author: "LaTeX with hyperref",
      publisher: "QA-TBH Publishers",
      dop: "01 Jan 2025",
      language: "English",
      price: "₹5,482.00",
      status: "Published",
      initials: "EL",
      coverGradient: "linear-gradient(135deg, #1e293b 0%, #334155 100%)",
    },
    {
      id: "b-tbh-2",
      title: "Principles of Modern Literary Studies",
      category: "Academic & Professional",
      isbn: "978-3-16-148410-0",
      author: "Dr. K. R. Varma",
      publisher: "QA-TBH Publishers",
      dop: "15 Feb 2025",
      language: "English",
      price: "₹450.00",
      status: "Published",
      initials: "PL",
      coverGradient: "linear-gradient(135deg, #0f766e 0%, #14b8a6 100%)",
    },
    {
      id: "b-tbh-3",
      title: "Heritage of South India",
      category: "History & Culture",
      isbn: "978-81-7023-112-9",
      author: "Nair & Associates",
      publisher: "QA-TBH Publishers",
      dop: "10 Mar 2025",
      language: "Malayalam",
      price: "₹380.00",
      status: "Published",
      initials: "HS",
      coverGradient: "linear-gradient(135deg, #854d0e 0%, #ca8a04 100%)",
    },
    {
      id: "b-tbh-4",
      title: "Digital Ecosystems & Publishers",
      category: "Computer Science & Tech",
      isbn: "978-93-5012-445-1",
      author: "TBH Editorial Board",
      publisher: "QA-TBH Publishers",
      dop: "05 Apr 2025",
      language: "English",
      price: "₹890.00",
      status: "Published",
      initials: "DE",
      coverGradient: "linear-gradient(135deg, #4338ca 0%, #6366f1 100%)",
    },
    {
      id: "b-tbh-5",
      title: "Foundations of Data Science",
      category: "Technology",
      isbn: "978-0-262-03384-8",
      author: "Prof. S. R. Menon",
      publisher: "QA-TBH Publishers",
      dop: "14 Jul 2025",
      language: "English",
      price: "₹1,150.00",
      status: "Published",
      initials: "FD",
      coverGradient: "linear-gradient(135deg, #15803d 0%, #22c55e 100%)",
    },
    {
      id: "b-tbh-6",
      title: "Philosophy & Human Thought",
      category: "Philosophy",
      isbn: "978-0-674-00661-4",
      author: "Dr. A. P. Sharma",
      publisher: "QA-TBH Publishers",
      dop: "11 Oct 2025",
      language: "English",
      price: "₹520.00",
      status: "Published",
      initials: "PH",
      coverGradient: "linear-gradient(135deg, #374151 0%, #6b7280 100%)",
    },
    {
      id: "b-tbh-7",
      title: "Environmental Policy & Futures",
      category: "Sciences & Ecology",
      isbn: "978-0-521-82559-7",
      author: "Green Earth Forum",
      publisher: "QA-TBH Publishers",
      dop: "01 Dec 2025",
      language: "English",
      price: "₹890.00",
      status: "Published",
      initials: "EP",
      coverGradient: "linear-gradient(135deg, #047857 0%, #10b981 100%)",
    },
    {
      id: "b-tbh-8",
      title: "The World of Children's Literature",
      category: "Children's Books",
      isbn: "978-0-06-025492-6",
      author: "Maya Sen",
      publisher: "QA-TBH Publishers",
      dop: "15 Jan 2026",
      language: "English",
      price: "₹250.00",
      status: "Published",
      initials: "WC",
      coverGradient: "linear-gradient(135deg, #b45309 0%, #f59e0b 100%)",
    },
    {
      id: "b-tbh-9",
      title: "Advanced Macroeconomics",
      category: "Economics & Finance",
      isbn: "978-0-07-351137-5",
      author: "R. K. Gupta",
      publisher: "QA-TBH Publishers",
      dop: "20 Feb 2026",
      language: "English",
      price: "₹1,420.00",
      status: "Published",
      initials: "AM",
      coverGradient: "linear-gradient(135deg, #1d4ed8 0%, #3b82f6 100%)",
    },
    {
      id: "b-tbh-10",
      title: "Contemporary Architectural Forms",
      category: "Architecture & Design",
      isbn: "978-0-500-28560-2",
      author: "Vikram Singhania",
      publisher: "QA-TBH Publishers",
      dop: "08 Apr 2026",
      language: "English",
      price: "₹1,850.00",
      status: "Published",
      initials: "CA",
      coverGradient: "linear-gradient(135deg, #475569 0%, #0f172a 100%)",
    },
    {
      id: "b-tbh-11",
      title: "Introduction to Computational Linguistics",
      category: "Computer Science",
      isbn: "978-0-19-920438-0",
      author: "Dr. Ananya Roy",
      publisher: "QA-TBH Publishers",
      dop: "12 May 2026",
      language: "English",
      price: "₹920.00",
      status: "Published",
      initials: "CL",
      coverGradient: "linear-gradient(135deg, #0284c7 0%, #0369a1 100%)",
    },
  ],

  // QA (Publisher - 1 title)
  "pa-9": [
    {
      id: "b-qa-1",
      title: "Essential Software Quality Assurance Guide",
      category: "Technology",
      isbn: "978-0-13-235088-4",
      author: "QA Engineering Team",
      publisher: "QA",
      dop: "14 Jan 2025",
      language: "English",
      price: "₹780.00",
      status: "Published",
      initials: "QA",
      coverGradient: "linear-gradient(135deg, #059669 0%, #047857 100%)",
    },
  ],

  // OBook Publication (Publisher - 5 titles)
  "pa-10": [
    {
      id: "b-ob-1",
      title: "Whispers of the Monsoon",
      category: "Poetry",
      isbn: "978-81-291-1234-1",
      author: "Ritu Chawla",
      publisher: "OBook Publication",
      dop: "10 Feb 2025",
      language: "English",
      price: "₹320.00",
      status: "Published",
      initials: "WM",
      coverGradient: "linear-gradient(135deg, #0284c7 0%, #0369a1 100%)",
    },
    {
      id: "b-ob-2",
      title: "Tales from the Western Ghats",
      category: "Fiction & Folklore",
      isbn: "978-81-291-5678-2",
      author: "Praveen Nair",
      publisher: "OBook Publication",
      dop: "02 Mar 2025",
      language: "Malayalam",
      price: "₹290.00",
      status: "Published",
      initials: "TW",
      coverGradient: "linear-gradient(135deg, #15803d 0%, #166534 100%)",
    },
    {
      id: "b-ob-3",
      title: "Journey Through Modern Kerala",
      category: "Travel & Culture",
      isbn: "978-81-291-9012-3",
      author: "Mathew Thomas",
      publisher: "OBook Publication",
      dop: "18 Apr 2025",
      language: "English",
      price: "₹450.00",
      status: "Published",
      initials: "JM",
      coverGradient: "linear-gradient(135deg, #d97706 0%, #b45309 100%)",
    },
    {
      id: "b-ob-4",
      title: "Flavours of Malabar",
      category: "Cookery & Lifestyle",
      isbn: "978-81-291-3456-4",
      author: "Chef Rasheed",
      publisher: "OBook Publication",
      dop: "24 May 2025",
      language: "English",
      price: "₹599.00",
      status: "Published",
      initials: "FM",
      coverGradient: "linear-gradient(135deg, #dc2626 0%, #991b1b 100%)",
    },
    {
      id: "b-ob-5",
      title: "Echoes of the Backwaters",
      category: "Literary Fiction",
      isbn: "978-81-291-7890-5",
      author: "Asha Varghese",
      publisher: "OBook Publication",
      dop: "12 Jun 2025",
      language: "English",
      price: "₹380.00",
      status: "Published",
      initials: "EB",
      coverGradient: "linear-gradient(135deg, #7c3aed 0%, #581c87 100%)",
    },
  ],

  // Horizon Press (Publisher - 14 titles)
  "pa-11": [
    {
      id: "b-hp-1",
      title: "Principles of Quantum Computing",
      category: "Science & Tech",
      isbn: "978-0-19-850123-1",
      author: "Dr. A. Sen",
      publisher: "Horizon Press",
      dop: "12 Jan 2025",
      language: "English",
      price: "₹1,250.00",
      status: "Published",
      initials: "PQ",
      coverGradient: "linear-gradient(135deg, #2563eb 0%, #1d4ed8 100%)",
    },
    {
      id: "b-hp-2",
      title: "Global Political Economy",
      category: "Social Sciences",
      isbn: "978-0-19-850124-2",
      author: "S. K. Mukherjee",
      publisher: "Horizon Press",
      dop: "20 Jan 2025",
      language: "English",
      price: "₹950.00",
      status: "Published",
      initials: "GP",
      coverGradient: "linear-gradient(135deg, #b45309 0%, #78350f 100%)",
    },
    {
      id: "b-hp-3",
      title: "Modern Constitutional Law",
      category: "Law & Governance",
      isbn: "978-0-19-850125-3",
      author: "Adv. Meenakshi Rao",
      publisher: "Horizon Press",
      dop: "04 Feb 2025",
      language: "English",
      price: "₹1,400.00",
      status: "Published",
      initials: "MC",
      coverGradient: "linear-gradient(135deg, #334155 0%, #0f172a 100%)",
    },
    {
      id: "b-hp-4",
      title: "Biotechnology & Future Medicine",
      category: "Medical Sciences",
      isbn: "978-0-19-850126-4",
      author: "Dr. Kavita Joshi",
      publisher: "Horizon Press",
      dop: "18 Feb 2025",
      language: "English",
      price: "₹1,650.00",
      status: "Published",
      initials: "BF",
      coverGradient: "linear-gradient(135deg, #059669 0%, #064e3b 100%)",
    },
    {
      id: "b-hp-5",
      title: "The Renaissance of Indian Philosophy",
      category: "Philosophy",
      isbn: "978-0-19-850127-5",
      author: "Prof. Devdutt Shastri",
      publisher: "Horizon Press",
      dop: "02 Mar 2025",
      language: "English",
      price: "₹720.00",
      status: "Published",
      initials: "RI",
      coverGradient: "linear-gradient(135deg, #ea580c 0%, #9a3412 100%)",
    },
    {
      id: "b-hp-6",
      title: "Sustainable Urban Design",
      category: "Architecture",
      isbn: "978-0-19-850128-6",
      author: "Rohit Deshmukh",
      publisher: "Horizon Press",
      dop: "15 Mar 2025",
      language: "English",
      price: "₹1,180.00",
      status: "Published",
      initials: "SU",
      coverGradient: "linear-gradient(135deg, #0891b2 0%, #164e63 100%)",
    },
    {
      id: "b-hp-7",
      title: "Artificial Intelligence in Healthcare",
      category: "Technology",
      isbn: "978-0-19-850129-7",
      author: "Dr. Arvind Chari",
      publisher: "Horizon Press",
      dop: "28 Mar 2025",
      language: "English",
      price: "₹1,520.00",
      status: "Published",
      initials: "AI",
      coverGradient: "linear-gradient(135deg, #4f46e5 0%, #312e81 100%)",
    },
    {
      id: "b-hp-8",
      title: "Foundations of Corporate Finance",
      category: "Business & Management",
      isbn: "978-0-19-850130-3",
      author: "Sunil Bajaj",
      publisher: "Horizon Press",
      dop: "10 Apr 2025",
      language: "English",
      price: "₹980.00",
      status: "Published",
      initials: "FC",
      coverGradient: "linear-gradient(135deg, #16a34a 0%, #14532d 100%)",
    },
    {
      id: "b-hp-9",
      title: "Voices from the Freedom Movement",
      category: "History",
      isbn: "978-0-19-850131-0",
      author: "T. N. Madhavan",
      publisher: "Horizon Press",
      dop: "22 Apr 2025",
      language: "English",
      price: "₹540.00",
      status: "Published",
      initials: "VF",
      coverGradient: "linear-gradient(135deg, #c026d3 0%, #701a75 100%)",
    },
    {
      id: "b-hp-10",
      title: "Environmental Law and Treaties",
      category: "Law",
      isbn: "978-0-19-850132-7",
      author: "Pooja Hegde",
      publisher: "Horizon Press",
      dop: "05 May 2025",
      language: "English",
      price: "₹1,100.00",
      status: "Published",
      initials: "EL",
      coverGradient: "linear-gradient(135deg, #0d9488 0%, #115e59 100%)",
    },
    {
      id: "b-hp-11",
      title: "Applied Microeconomics",
      category: "Economics",
      isbn: "978-0-19-850133-4",
      author: "Dr. B. K. Raman",
      publisher: "Horizon Press",
      dop: "18 May 2025",
      language: "English",
      price: "₹860.00",
      status: "Published",
      initials: "AM",
      coverGradient: "linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%)",
    },
    {
      id: "b-hp-12",
      title: "The Art of Documentary Filmmaking",
      category: "Arts & Media",
      isbn: "978-0-19-850134-1",
      author: "Shekhar Kapur",
      publisher: "Horizon Press",
      dop: "01 Jun 2025",
      language: "English",
      price: "₹790.00",
      status: "Published",
      initials: "AD",
      coverGradient: "linear-gradient(135deg, #e11d48 0%, #881337 100%)",
    },
    {
      id: "b-hp-13",
      title: "Clinical Psychology Handbook",
      category: "Psychology",
      isbn: "978-0-19-850135-8",
      author: "Dr. Neha Kapoor",
      publisher: "Horizon Press",
      dop: "15 Jun 2025",
      language: "English",
      price: "₹1,320.00",
      status: "Published",
      initials: "CP",
      coverGradient: "linear-gradient(135deg, #9333ea 0%, #581c87 100%)",
    },
    {
      id: "b-hp-14",
      title: "Renewable Energy Systems",
      category: "Engineering",
      isbn: "978-0-19-850136-5",
      author: "Prof. Vinod Mehta",
      publisher: "Horizon Press",
      dop: "28 Jun 2025",
      language: "English",
      price: "₹1,450.00",
      status: "Published",
      initials: "RE",
      coverGradient: "linear-gradient(135deg, #ca8a04 0%, #713f12 100%)",
    },
  ],

  // Aarav Sharma (Author - 3 titles)
  "pa-12": [
    {
      id: "b-as-1",
      title: "Shadows of the Delhi Fort",
      category: "Mystery & Thriller",
      isbn: "978-93-8765-101-1",
      author: "Aarav Sharma",
      publisher: "Horizon Press",
      dop: "15 Jan 2025",
      language: "English",
      price: "₹399.00",
      status: "Published",
      initials: "SF",
      coverGradient: "linear-gradient(135deg, #1e293b 0%, #0f172a 100%)",
    },
    {
      id: "b-as-2",
      title: "The Forgotten Monolith",
      category: "Adventure Fiction",
      isbn: "978-93-8765-102-2",
      author: "Aarav Sharma",
      publisher: "Apex Lit House",
      dop: "20 Feb 2025",
      language: "English",
      price: "₹350.00",
      status: "Published",
      initials: "FM",
      coverGradient: "linear-gradient(135deg, #0d9488 0%, #134e4a 100%)",
    },
    {
      id: "b-as-3",
      title: "Midnight in Varanasi",
      category: "Literary Fiction",
      isbn: "978-93-8765-103-3",
      author: "Aarav Sharma",
      publisher: "Beacon Publishing",
      dop: "05 Apr 2025",
      language: "Hindi",
      price: "₹280.00",
      status: "Published",
      initials: "MV",
      coverGradient: "linear-gradient(135deg, #ea580c 0%, #7c2d12 100%)",
    },
  ],

  // Apex Lit House (Publisher - 8 titles)
  "pa-13": [
    {
      id: "b-alh-1",
      title: "Chronicles of Tamil Sangam",
      category: "Classical Literature",
      isbn: "978-81-7000-210-1",
      author: "K. Subramanian",
      publisher: "Apex Lit House",
      dop: "10 Feb 2025",
      language: "Tamil",
      price: "₹420.00",
      status: "Published",
      initials: "TS",
      coverGradient: "linear-gradient(135deg, #b91c1c 0%, #7f1d1d 100%)",
    },
    {
      id: "b-alh-2",
      title: "Modern Dravidian Poetry",
      category: "Poetry",
      isbn: "978-81-7000-211-2",
      author: "M. Selvaraj",
      publisher: "Apex Lit House",
      dop: "22 Feb 2025",
      language: "Tamil",
      price: "₹280.00",
      status: "Published",
      initials: "DP",
      coverGradient: "linear-gradient(135deg, #7c3aed 0%, #4c1d95 100%)",
    },
    {
      id: "b-alh-3",
      title: "The Architecture of Thanjavur",
      category: "Architecture & History",
      isbn: "978-81-7000-212-3",
      author: "Dr. R. Nagaswamy",
      publisher: "Apex Lit House",
      dop: "08 Mar 2025",
      language: "English",
      price: "₹850.00",
      status: "Published",
      initials: "AT",
      coverGradient: "linear-gradient(135deg, #c2410c 0%, #7c2d12 100%)",
    },
    {
      id: "b-alh-4",
      title: "Legends of the Coromandel Coast",
      category: "Folklore",
      isbn: "978-81-7000-213-4",
      author: "Geetha Krishnan",
      publisher: "Apex Lit House",
      dop: "19 Mar 2025",
      language: "English",
      price: "₹340.00",
      status: "Published",
      initials: "LC",
      coverGradient: "linear-gradient(135deg, #0284c7 0%, #075985 100%)",
    },
    {
      id: "b-alh-5",
      title: "Carnatic Music Traditions",
      category: "Performing Arts",
      isbn: "978-81-7000-214-5",
      author: "Vidwan S. Ramanathan",
      publisher: "Apex Lit House",
      dop: "04 Apr 2025",
      language: "English",
      price: "₹560.00",
      status: "Published",
      initials: "CM",
      coverGradient: "linear-gradient(135deg, #d97706 0%, #78350f 100%)",
    },
    {
      id: "b-alh-6",
      title: "Rivers of the South",
      category: "Ecology & Geography",
      isbn: "978-81-7000-215-6",
      author: "P. V. Radhakrishnan",
      publisher: "Apex Lit House",
      dop: "15 Apr 2025",
      language: "English",
      price: "₹490.00",
      status: "Published",
      initials: "RS",
      coverGradient: "linear-gradient(135deg, #059669 0%, #064e3b 100%)",
    },
    {
      id: "b-alh-7",
      title: "Short Plays for the Contemporary Stage",
      category: "Drama",
      isbn: "978-81-7000-216-7",
      author: "K. Balachander Group",
      publisher: "Apex Lit House",
      dop: "02 May 2025",
      language: "Tamil",
      price: "₹310.00",
      status: "Published",
      initials: "SP",
      coverGradient: "linear-gradient(135deg, #4338ca 0%, #312e81 100%)",
    },
    {
      id: "b-alh-8",
      title: "Philosophy of Thirukkural in Daily Life",
      category: "Philosophy",
      isbn: "978-81-7000-217-8",
      author: "Prof. N. Murugesan",
      publisher: "Apex Lit House",
      dop: "14 May 2025",
      language: "English",
      price: "₹450.00",
      status: "Published",
      initials: "PT",
      coverGradient: "linear-gradient(135deg, #475569 0%, #1e293b 100%)",
    },
  ],

  // Meera Nair (Author - 2 titles)
  "pa-14": [
    {
      id: "b-mn-1",
      title: "Monsoon Letters",
      category: "Contemporary Fiction",
      isbn: "978-93-5128-401-1",
      author: "Meera Nair",
      publisher: "OBook Publication",
      dop: "12 Feb 2025",
      language: "English",
      price: "₹350.00",
      status: "Published",
      initials: "ML",
      coverGradient: "linear-gradient(135deg, #0284c7 0%, #0369a1 100%)",
    },
    {
      id: "b-mn-2",
      title: "The House by the River",
      category: "Literary Fiction",
      isbn: "978-93-5128-402-2",
      author: "Meera Nair",
      publisher: "QA-TBH Publishers",
      dop: "28 Apr 2025",
      language: "Malayalam",
      price: "₹310.00",
      status: "Published",
      initials: "HR",
      coverGradient: "linear-gradient(135deg, #059669 0%, #047857 100%)",
    },
  ],
};

export function getBooksForAccount(
  accountId: string,
  accountName?: string,
  accountType?: string
): PublisherAuthorBook[] {
  // Check exact account ID match
  if (BOOKS_BY_ACCOUNT[accountId]) {
    return BOOKS_BY_ACCOUNT[accountId];
  }

  // Fallback: search across all books if author/publisher name matches
  if (accountName) {
    const matched: PublisherAuthorBook[] = [];
    const lowerName = accountName.toLowerCase();

    Object.values(BOOKS_BY_ACCOUNT).forEach((bookList) => {
      bookList.forEach((b) => {
        if (
          (accountType === "Author" && b.author.toLowerCase().includes(lowerName)) ||
          (accountType === "Publisher" && b.publisher.toLowerCase().includes(lowerName))
        ) {
          if (!matched.some((m) => m.id === b.id)) {
            matched.push(b);
          }
        }
      });
    });

    if (matched.length > 0) {
      return matched;
    }
  }

  return [];
}
