/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LibraryUserRouteImport } from './routes/library-user'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublisherIndexRouteImport } from './routes/publisher/index'
import { Route as PbAdminIndexRouteImport } from './routes/pb-admin/index'
import { Route as PbAdminLibIndexRouteImport } from './routes/pb-admin-lib/index'
import { Route as LibraryAdminIndexRouteImport } from './routes/library-admin/index'
import { Route as AuthorIndexRouteImport } from './routes/author/index'
import { Route as PublisherSupportRouteImport } from './routes/publisher/support'
import { Route as PublisherSettingsRouteImport } from './routes/publisher/settings'
import { Route as PublisherSalesReportRouteImport } from './routes/publisher/sales-report'
import { Route as PublisherProfileRouteImport } from './routes/publisher/profile'
import { Route as PublisherMarginReportRouteImport } from './routes/publisher/margin-report'
import { Route as PublisherBankAccountsRouteImport } from './routes/publisher/bank-accounts'
import { Route as PbAdminViewsReportRouteImport } from './routes/pb-admin/views-report'
import { Route as PbAdminTermsConditionsRouteImport } from './routes/pb-admin/terms-conditions'
import { Route as PbAdminSettingsRouteImport } from './routes/pb-admin/settings'
import { Route as PbAdminSalesReportRouteImport } from './routes/pb-admin/sales-report'
import { Route as PbAdminQuizzesRewardsRouteImport } from './routes/pb-admin/quizzes-rewards'
import { Route as PbAdminQuizzRewardsRouteImport } from './routes/pb-admin/quizz-rewards'
import { Route as PbAdminPublishersAuthorsRouteImport } from './routes/pb-admin/publishers-authors'
import { Route as PbAdminPromoCodesRouteImport } from './routes/pb-admin/promo-codes'
import { Route as PbAdminProfileRouteImport } from './routes/pb-admin/profile'
import { Route as PbAdminPrivacyPolicyRouteImport } from './routes/pb-admin/privacy-policy'
import { Route as PbAdminNotificationsRouteImport } from './routes/pb-admin/notifications'
import { Route as PbAdminMergeAuthorsRouteImport } from './routes/pb-admin/merge-authors'
import { Route as PbAdminMarginReportRouteImport } from './routes/pb-admin/margin-report'
import { Route as PbAdminFeaturedCollectionsRouteImport } from './routes/pb-admin/featured-collections'
import { Route as PbAdminCustomersRouteImport } from './routes/pb-admin/customers'
import { Route as PbAdminCommissionRatesRouteImport } from './routes/pb-admin/commission-rates'
import { Route as PbAdminCategoriesRouteImport } from './routes/pb-admin/categories'
import { Route as PbAdminCartViewRouteImport } from './routes/pb-admin/cart-view'
import { Route as PbAdminCartAnalysisRouteImport } from './routes/pb-admin/cart-analysis'
import { Route as PbAdminAuthorManagementRouteImport } from './routes/pb-admin/author-management'
import { Route as PbAdminAuditLogRouteImport } from './routes/pb-admin/audit-log'
import { Route as PbAdminAdminUsersRouteImport } from './routes/pb-admin/admin-users'
import { Route as PbAdminLibTermsConditionsRouteImport } from './routes/pb-admin-lib/terms-conditions'
import { Route as PbAdminLibSettingsRouteImport } from './routes/pb-admin-lib/settings'
import { Route as PbAdminLibReportsRouteImport } from './routes/pb-admin-lib/reports'
import { Route as PbAdminLibPrivacyPolicyRouteImport } from './routes/pb-admin-lib/privacy-policy'
import { Route as PbAdminLibOrdersRouteImport } from './routes/pb-admin-lib/orders'
import { Route as PbAdminLibLibrariesRouteImport } from './routes/pb-admin-lib/libraries'
import { Route as PbAdminLibCloneRouteImport } from './routes/pb-admin-lib/clone'
import { Route as PbAdminLibCatalogueRouteImport } from './routes/pb-admin-lib/catalogue'
import { Route as LibraryUserProfileRouteImport } from './routes/library-user.profile'
import { Route as LibraryAdminUsersRouteImport } from './routes/library-admin/users'
import { Route as LibraryAdminSupportRouteImport } from './routes/library-admin/support'
import { Route as LibraryAdminRequestsRouteImport } from './routes/library-admin/requests'
import { Route as LibraryAdminReportsRouteImport } from './routes/library-admin/reports'
import { Route as LibraryAdminProfileRouteImport } from './routes/library-admin/profile'
import { Route as LibraryAdminOrdersRouteImport } from './routes/library-admin/orders'
import { Route as LibraryAdminManageEbooksRouteImport } from './routes/library-admin/manage-ebooks'
import { Route as LibraryAdminDepartmentsRouteImport } from './routes/library-admin/departments'
import { Route as LibraryAdminCoursesRouteImport } from './routes/library-admin/courses'
import { Route as LibraryAdminCatalogueRouteImport } from './routes/library-admin/catalogue'
import { Route as LibraryAdminCartRouteImport } from './routes/library-admin/cart'
import { Route as LibraryAdminBannersRouteImport } from './routes/library-admin/banners'
import { Route as AuthorProfileRouteImport } from './routes/author/profile'
import { Route as PublisherPromoCodesIndexRouteImport } from './routes/publisher/promo-codes.index'
import { Route as PublisherCatalogueIndexRouteImport } from './routes/publisher/catalogue.index'
import { Route as PublisherCatalogueImportIndexRouteImport } from './routes/publisher/catalogue-import.index'
import { Route as PublisherBundlesIndexRouteImport } from './routes/publisher/bundles.index'
import { Route as PbAdminTitlesIndexRouteImport } from './routes/pb-admin/titles.index'
import { Route as PbAdminBundlesIndexRouteImport } from './routes/pb-admin/bundles.index'
import { Route as PublisherPromoCodesNewRouteImport } from './routes/publisher/promo-codes.new'
import { Route as PublisherPromoCodesPromoIdRouteImport } from './routes/publisher/promo-codes.$promoId'
import { Route as PublisherCatalogueNewRouteImport } from './routes/publisher/catalogue.new'
import { Route as PublisherCatalogueBookIdRouteImport } from './routes/publisher/catalogue.$bookId'
import { Route as PublisherCatalogueImportNewRouteImport } from './routes/publisher/catalogue-import.new'
import { Route as PublisherCatalogueImportFileNameRouteImport } from './routes/publisher/catalogue-import.$fileName'
import { Route as PublisherBundlesNewRouteImport } from './routes/publisher/bundles.new'
import { Route as PublisherBundlesBundleIdRouteImport } from './routes/publisher/bundles.$bundleId'
import { Route as PbAdminTitlesNewRouteImport } from './routes/pb-admin/titles.new'
import { Route as PbAdminTitlesBookIdRouteImport } from './routes/pb-admin/titles.$bookId'
import { Route as PbAdminTermsConditionsNewRouteImport } from './routes/pb-admin/terms-conditions_.new'
import { Route as PbAdminTermsConditionsIdRouteImport } from './routes/pb-admin/terms-conditions_.$id'
import { Route as PbAdminPublishersAuthorsIdRouteImport } from './routes/pb-admin/publishers-authors.$id'
import { Route as PbAdminPrivacyPolicyNewRouteImport } from './routes/pb-admin/privacy-policy_.new'
import { Route as PbAdminPrivacyPolicyIdRouteImport } from './routes/pb-admin/privacy-policy_.$id'
import { Route as PbAdminMarketingSitemapRouteImport } from './routes/pb-admin/marketing.sitemap'
import { Route as PbAdminMarketingSchemaMetaRouteImport } from './routes/pb-admin/marketing.schema-meta'
import { Route as PbAdminCommissionRatesIdRouteImport } from './routes/pb-admin/commission-rates_/$id'
import { Route as PbAdminBundlesNewRouteImport } from './routes/pb-admin/bundles.new'
import { Route as PbAdminBundlesBundleIdRouteImport } from './routes/pb-admin/bundles.$bundleId'
import { Route as PbAdminAuthorManagementAuthorIdRouteImport } from './routes/pb-admin/author-management.$authorId'
import { Route as PbAdminAdBannersPopupRouteImport } from './routes/pb-admin/ad-banners.popup'
import { Route as PbAdminAdBannersImageRouteImport } from './routes/pb-admin/ad-banners.image'
import { Route as PbAdminLibTermsConditionsNewRouteImport } from './routes/pb-admin-lib/terms-conditions_.new'
import { Route as PbAdminLibTermsConditionsIdRouteImport } from './routes/pb-admin-lib/terms-conditions_.$id'
import { Route as PbAdminLibPrivacyPolicyNewRouteImport } from './routes/pb-admin-lib/privacy-policy_.new'
import { Route as PbAdminLibPrivacyPolicyIdRouteImport } from './routes/pb-admin-lib/privacy-policy_.$id'
import { Route as PbAdminLibOrdersIdRouteImport } from './routes/pb-admin-lib/orders_.$id'
import { Route as PbAdminLibLibrariesNewRouteImport } from './routes/pb-admin-lib/libraries_.new'
import { Route as PbAdminLibLibrariesIdRouteImport } from './routes/pb-admin-lib/libraries_.$id'
import { Route as PbAdminPublishersAuthorsIdTitlesRouteImport } from './routes/pb-admin/publishers-authors.$id.titles'

const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryUserRoute = LibraryUserRouteImport.update({
  id: '/library-user',
  path: '/library-user',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherIndexRoute = PublisherIndexRouteImport.update({
  id: '/publisher/',
  path: '/publisher/',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminIndexRoute = PbAdminIndexRouteImport.update({
  id: '/pb-admin/',
  path: '/pb-admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminLibIndexRoute = PbAdminLibIndexRouteImport.update({
  id: '/pb-admin-lib/',
  path: '/pb-admin-lib/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryAdminIndexRoute = LibraryAdminIndexRouteImport.update({
  id: '/library-admin/',
  path: '/library-admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorIndexRoute = AuthorIndexRouteImport.update({
  id: '/author/',
  path: '/author/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherSupportRoute = PublisherSupportRouteImport.update({
  id: '/publisher/support',
  path: '/publisher/support',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherSettingsRoute = PublisherSettingsRouteImport.update({
  id: '/publisher/settings',
  path: '/publisher/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherSalesReportRoute = PublisherSalesReportRouteImport.update({
  id: '/publisher/sales-report',
  path: '/publisher/sales-report',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherProfileRoute = PublisherProfileRouteImport.update({
  id: '/publisher/profile',
  path: '/publisher/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherMarginReportRoute = PublisherMarginReportRouteImport.update({
  id: '/publisher/margin-report',
  path: '/publisher/margin-report',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherBankAccountsRoute = PublisherBankAccountsRouteImport.update({
  id: '/publisher/bank-accounts',
  path: '/publisher/bank-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminViewsReportRoute = PbAdminViewsReportRouteImport.update({
  id: '/pb-admin/views-report',
  path: '/pb-admin/views-report',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminTermsConditionsRoute = PbAdminTermsConditionsRouteImport.update({
  id: '/pb-admin/terms-conditions',
  path: '/pb-admin/terms-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminSettingsRoute = PbAdminSettingsRouteImport.update({
  id: '/pb-admin/settings',
  path: '/pb-admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminSalesReportRoute = PbAdminSalesReportRouteImport.update({
  id: '/pb-admin/sales-report',
  path: '/pb-admin/sales-report',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminQuizzesRewardsRoute = PbAdminQuizzesRewardsRouteImport.update({
  id: '/pb-admin/quizzes-rewards',
  path: '/pb-admin/quizzes-rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminQuizzRewardsRoute = PbAdminQuizzRewardsRouteImport.update({
  id: '/pb-admin/quizz-rewards',
  path: '/pb-admin/quizz-rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminPublishersAuthorsRoute =
  PbAdminPublishersAuthorsRouteImport.update({
    id: '/pb-admin/publishers-authors',
    path: '/pb-admin/publishers-authors',
    getParentRoute: () => rootRouteImport,
  } as any)
const PbAdminPromoCodesRoute = PbAdminPromoCodesRouteImport.update({
  id: '/pb-admin/promo-codes',
  path: '/pb-admin/promo-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminProfileRoute = PbAdminProfileRouteImport.update({
  id: '/pb-admin/profile',
  path: '/pb-admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminPrivacyPolicyRoute = PbAdminPrivacyPolicyRouteImport.update({
  id: '/pb-admin/privacy-policy',
  path: '/pb-admin/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminNotificationsRoute = PbAdminNotificationsRouteImport.update({
  id: '/pb-admin/notifications',
  path: '/pb-admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminMergeAuthorsRoute = PbAdminMergeAuthorsRouteImport.update({
  id: '/pb-admin/merge-authors',
  path: '/pb-admin/merge-authors',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminMarginReportRoute = PbAdminMarginReportRouteImport.update({
  id: '/pb-admin/margin-report',
  path: '/pb-admin/margin-report',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminFeaturedCollectionsRoute =
  PbAdminFeaturedCollectionsRouteImport.update({
    id: '/pb-admin/featured-collections',
    path: '/pb-admin/featured-collections',
    getParentRoute: () => rootRouteImport,
  } as any)
const PbAdminCustomersRoute = PbAdminCustomersRouteImport.update({
  id: '/pb-admin/customers',
  path: '/pb-admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminCommissionRatesRoute = PbAdminCommissionRatesRouteImport.update({
  id: '/pb-admin/commission-rates',
  path: '/pb-admin/commission-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminCategoriesRoute = PbAdminCategoriesRouteImport.update({
  id: '/pb-admin/categories',
  path: '/pb-admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminCartViewRoute = PbAdminCartViewRouteImport.update({
  id: '/pb-admin/cart-view',
  path: '/pb-admin/cart-view',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminCartAnalysisRoute = PbAdminCartAnalysisRouteImport.update({
  id: '/pb-admin/cart-analysis',
  path: '/pb-admin/cart-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminAuthorManagementRoute = PbAdminAuthorManagementRouteImport.update({
  id: '/pb-admin/author-management',
  path: '/pb-admin/author-management',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminAuditLogRoute = PbAdminAuditLogRouteImport.update({
  id: '/pb-admin/audit-log',
  path: '/pb-admin/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminAdminUsersRoute = PbAdminAdminUsersRouteImport.update({
  id: '/pb-admin/admin-users',
  path: '/pb-admin/admin-users',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminLibTermsConditionsRoute =
  PbAdminLibTermsConditionsRouteImport.update({
    id: '/pb-admin-lib/terms-conditions',
    path: '/pb-admin-lib/terms-conditions',
    getParentRoute: () => rootRouteImport,
  } as any)
const PbAdminLibSettingsRoute = PbAdminLibSettingsRouteImport.update({
  id: '/pb-admin-lib/settings',
  path: '/pb-admin-lib/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminLibReportsRoute = PbAdminLibReportsRouteImport.update({
  id: '/pb-admin-lib/reports',
  path: '/pb-admin-lib/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminLibPrivacyPolicyRoute = PbAdminLibPrivacyPolicyRouteImport.update({
  id: '/pb-admin-lib/privacy-policy',
  path: '/pb-admin-lib/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminLibOrdersRoute = PbAdminLibOrdersRouteImport.update({
  id: '/pb-admin-lib/orders',
  path: '/pb-admin-lib/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminLibLibrariesRoute = PbAdminLibLibrariesRouteImport.update({
  id: '/pb-admin-lib/libraries',
  path: '/pb-admin-lib/libraries',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminLibCloneRoute = PbAdminLibCloneRouteImport.update({
  id: '/pb-admin-lib/clone',
  path: '/pb-admin-lib/clone',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminLibCatalogueRoute = PbAdminLibCatalogueRouteImport.update({
  id: '/pb-admin-lib/catalogue',
  path: '/pb-admin-lib/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryUserProfileRoute = LibraryUserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LibraryUserRoute,
} as any)
const LibraryAdminUsersRoute = LibraryAdminUsersRouteImport.update({
  id: '/library-admin/users',
  path: '/library-admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryAdminSupportRoute = LibraryAdminSupportRouteImport.update({
  id: '/library-admin/support',
  path: '/library-admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryAdminRequestsRoute = LibraryAdminRequestsRouteImport.update({
  id: '/library-admin/requests',
  path: '/library-admin/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryAdminReportsRoute = LibraryAdminReportsRouteImport.update({
  id: '/library-admin/reports',
  path: '/library-admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryAdminProfileRoute = LibraryAdminProfileRouteImport.update({
  id: '/library-admin/profile',
  path: '/library-admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryAdminOrdersRoute = LibraryAdminOrdersRouteImport.update({
  id: '/library-admin/orders',
  path: '/library-admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryAdminManageEbooksRoute =
  LibraryAdminManageEbooksRouteImport.update({
    id: '/library-admin/manage-ebooks',
    path: '/library-admin/manage-ebooks',
    getParentRoute: () => rootRouteImport,
  } as any)
const LibraryAdminDepartmentsRoute = LibraryAdminDepartmentsRouteImport.update({
  id: '/library-admin/departments',
  path: '/library-admin/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryAdminCoursesRoute = LibraryAdminCoursesRouteImport.update({
  id: '/library-admin/courses',
  path: '/library-admin/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryAdminCatalogueRoute = LibraryAdminCatalogueRouteImport.update({
  id: '/library-admin/catalogue',
  path: '/library-admin/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryAdminCartRoute = LibraryAdminCartRouteImport.update({
  id: '/library-admin/cart',
  path: '/library-admin/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryAdminBannersRoute = LibraryAdminBannersRouteImport.update({
  id: '/library-admin/banners',
  path: '/library-admin/banners',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorProfileRoute = AuthorProfileRouteImport.update({
  id: '/author/profile',
  path: '/author/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherPromoCodesIndexRoute =
  PublisherPromoCodesIndexRouteImport.update({
    id: '/publisher/promo-codes/',
    path: '/publisher/promo-codes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublisherCatalogueIndexRoute = PublisherCatalogueIndexRouteImport.update({
  id: '/publisher/catalogue/',
  path: '/publisher/catalogue/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherCatalogueImportIndexRoute =
  PublisherCatalogueImportIndexRouteImport.update({
    id: '/publisher/catalogue-import/',
    path: '/publisher/catalogue-import/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublisherBundlesIndexRoute = PublisherBundlesIndexRouteImport.update({
  id: '/publisher/bundles/',
  path: '/publisher/bundles/',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminTitlesIndexRoute = PbAdminTitlesIndexRouteImport.update({
  id: '/pb-admin/titles/',
  path: '/pb-admin/titles/',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminBundlesIndexRoute = PbAdminBundlesIndexRouteImport.update({
  id: '/pb-admin/bundles/',
  path: '/pb-admin/bundles/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherPromoCodesNewRoute = PublisherPromoCodesNewRouteImport.update({
  id: '/publisher/promo-codes/new',
  path: '/publisher/promo-codes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherPromoCodesPromoIdRoute =
  PublisherPromoCodesPromoIdRouteImport.update({
    id: '/publisher/promo-codes/$promoId',
    path: '/publisher/promo-codes/$promoId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublisherCatalogueNewRoute = PublisherCatalogueNewRouteImport.update({
  id: '/publisher/catalogue/new',
  path: '/publisher/catalogue/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherCatalogueBookIdRoute =
  PublisherCatalogueBookIdRouteImport.update({
    id: '/publisher/catalogue/$bookId',
    path: '/publisher/catalogue/$bookId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublisherCatalogueImportNewRoute =
  PublisherCatalogueImportNewRouteImport.update({
    id: '/publisher/catalogue-import/new',
    path: '/publisher/catalogue-import/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublisherCatalogueImportFileNameRoute =
  PublisherCatalogueImportFileNameRouteImport.update({
    id: '/publisher/catalogue-import/$fileName',
    path: '/publisher/catalogue-import/$fileName',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublisherBundlesNewRoute = PublisherBundlesNewRouteImport.update({
  id: '/publisher/bundles/new',
  path: '/publisher/bundles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherBundlesBundleIdRoute =
  PublisherBundlesBundleIdRouteImport.update({
    id: '/publisher/bundles/$bundleId',
    path: '/publisher/bundles/$bundleId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PbAdminTitlesNewRoute = PbAdminTitlesNewRouteImport.update({
  id: '/pb-admin/titles/new',
  path: '/pb-admin/titles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminTitlesBookIdRoute = PbAdminTitlesBookIdRouteImport.update({
  id: '/pb-admin/titles/$bookId',
  path: '/pb-admin/titles/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminTermsConditionsNewRoute =
  PbAdminTermsConditionsNewRouteImport.update({
    id: '/pb-admin/terms-conditions_/new',
    path: '/pb-admin/terms-conditions/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const PbAdminTermsConditionsIdRoute =
  PbAdminTermsConditionsIdRouteImport.update({
    id: '/pb-admin/terms-conditions_/$id',
    path: '/pb-admin/terms-conditions/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const PbAdminPublishersAuthorsIdRoute =
  PbAdminPublishersAuthorsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => PbAdminPublishersAuthorsRoute,
  } as any)
const PbAdminPrivacyPolicyNewRoute = PbAdminPrivacyPolicyNewRouteImport.update({
  id: '/pb-admin/privacy-policy_/new',
  path: '/pb-admin/privacy-policy/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminPrivacyPolicyIdRoute = PbAdminPrivacyPolicyIdRouteImport.update({
  id: '/pb-admin/privacy-policy_/$id',
  path: '/pb-admin/privacy-policy/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminMarketingSitemapRoute = PbAdminMarketingSitemapRouteImport.update({
  id: '/pb-admin/marketing/sitemap',
  path: '/pb-admin/marketing/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminMarketingSchemaMetaRoute =
  PbAdminMarketingSchemaMetaRouteImport.update({
    id: '/pb-admin/marketing/schema-meta',
    path: '/pb-admin/marketing/schema-meta',
    getParentRoute: () => rootRouteImport,
  } as any)
const PbAdminCommissionRatesIdRoute =
  PbAdminCommissionRatesIdRouteImport.update({
    id: '/pb-admin/commission-rates_/$id',
    path: '/pb-admin/commission-rates/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const PbAdminBundlesNewRoute = PbAdminBundlesNewRouteImport.update({
  id: '/pb-admin/bundles/new',
  path: '/pb-admin/bundles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminBundlesBundleIdRoute = PbAdminBundlesBundleIdRouteImport.update({
  id: '/pb-admin/bundles/$bundleId',
  path: '/pb-admin/bundles/$bundleId',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminAuthorManagementAuthorIdRoute =
  PbAdminAuthorManagementAuthorIdRouteImport.update({
    id: '/$authorId',
    path: '/$authorId',
    getParentRoute: () => PbAdminAuthorManagementRoute,
  } as any)
const PbAdminAdBannersPopupRoute = PbAdminAdBannersPopupRouteImport.update({
  id: '/pb-admin/ad-banners/popup',
  path: '/pb-admin/ad-banners/popup',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminAdBannersImageRoute = PbAdminAdBannersImageRouteImport.update({
  id: '/pb-admin/ad-banners/image',
  path: '/pb-admin/ad-banners/image',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminLibTermsConditionsNewRoute =
  PbAdminLibTermsConditionsNewRouteImport.update({
    id: '/pb-admin-lib/terms-conditions_/new',
    path: '/pb-admin-lib/terms-conditions/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const PbAdminLibTermsConditionsIdRoute =
  PbAdminLibTermsConditionsIdRouteImport.update({
    id: '/pb-admin-lib/terms-conditions_/$id',
    path: '/pb-admin-lib/terms-conditions/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const PbAdminLibPrivacyPolicyNewRoute =
  PbAdminLibPrivacyPolicyNewRouteImport.update({
    id: '/pb-admin-lib/privacy-policy_/new',
    path: '/pb-admin-lib/privacy-policy/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const PbAdminLibPrivacyPolicyIdRoute =
  PbAdminLibPrivacyPolicyIdRouteImport.update({
    id: '/pb-admin-lib/privacy-policy_/$id',
    path: '/pb-admin-lib/privacy-policy/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const PbAdminLibOrdersIdRoute = PbAdminLibOrdersIdRouteImport.update({
  id: '/pb-admin-lib/orders_/$id',
  path: '/pb-admin-lib/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminLibLibrariesNewRoute = PbAdminLibLibrariesNewRouteImport.update({
  id: '/pb-admin-lib/libraries_/new',
  path: '/pb-admin-lib/libraries/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminLibLibrariesIdRoute = PbAdminLibLibrariesIdRouteImport.update({
  id: '/pb-admin-lib/libraries_/$id',
  path: '/pb-admin-lib/libraries/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PbAdminPublishersAuthorsIdTitlesRoute =
  PbAdminPublishersAuthorsIdTitlesRouteImport.update({
    id: '/titles',
    path: '/titles',
    getParentRoute: () => PbAdminPublishersAuthorsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library-user': typeof LibraryUserRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/author/profile': typeof AuthorProfileRoute
  '/library-admin/banners': typeof LibraryAdminBannersRoute
  '/library-admin/cart': typeof LibraryAdminCartRoute
  '/library-admin/catalogue': typeof LibraryAdminCatalogueRoute
  '/library-admin/courses': typeof LibraryAdminCoursesRoute
  '/library-admin/departments': typeof LibraryAdminDepartmentsRoute
  '/library-admin/manage-ebooks': typeof LibraryAdminManageEbooksRoute
  '/library-admin/orders': typeof LibraryAdminOrdersRoute
  '/library-admin/profile': typeof LibraryAdminProfileRoute
  '/library-admin/reports': typeof LibraryAdminReportsRoute
  '/library-admin/requests': typeof LibraryAdminRequestsRoute
  '/library-admin/support': typeof LibraryAdminSupportRoute
  '/library-admin/users': typeof LibraryAdminUsersRoute
  '/library-user/profile': typeof LibraryUserProfileRoute
  '/pb-admin-lib/catalogue': typeof PbAdminLibCatalogueRoute
  '/pb-admin-lib/clone': typeof PbAdminLibCloneRoute
  '/pb-admin-lib/libraries': typeof PbAdminLibLibrariesRoute
  '/pb-admin-lib/orders': typeof PbAdminLibOrdersRoute
  '/pb-admin-lib/privacy-policy': typeof PbAdminLibPrivacyPolicyRoute
  '/pb-admin-lib/reports': typeof PbAdminLibReportsRoute
  '/pb-admin-lib/settings': typeof PbAdminLibSettingsRoute
  '/pb-admin-lib/terms-conditions': typeof PbAdminLibTermsConditionsRoute
  '/pb-admin/admin-users': typeof PbAdminAdminUsersRoute
  '/pb-admin/audit-log': typeof PbAdminAuditLogRoute
  '/pb-admin/author-management': typeof PbAdminAuthorManagementRouteWithChildren
  '/pb-admin/cart-analysis': typeof PbAdminCartAnalysisRoute
  '/pb-admin/cart-view': typeof PbAdminCartViewRoute
  '/pb-admin/categories': typeof PbAdminCategoriesRoute
  '/pb-admin/commission-rates': typeof PbAdminCommissionRatesRoute
  '/pb-admin/customers': typeof PbAdminCustomersRoute
  '/pb-admin/featured-collections': typeof PbAdminFeaturedCollectionsRoute
  '/pb-admin/margin-report': typeof PbAdminMarginReportRoute
  '/pb-admin/merge-authors': typeof PbAdminMergeAuthorsRoute
  '/pb-admin/notifications': typeof PbAdminNotificationsRoute
  '/pb-admin/privacy-policy': typeof PbAdminPrivacyPolicyRoute
  '/pb-admin/profile': typeof PbAdminProfileRoute
  '/pb-admin/promo-codes': typeof PbAdminPromoCodesRoute
  '/pb-admin/publishers-authors': typeof PbAdminPublishersAuthorsRouteWithChildren
  '/pb-admin/quizz-rewards': typeof PbAdminQuizzRewardsRoute
  '/pb-admin/quizzes-rewards': typeof PbAdminQuizzesRewardsRoute
  '/pb-admin/sales-report': typeof PbAdminSalesReportRoute
  '/pb-admin/settings': typeof PbAdminSettingsRoute
  '/pb-admin/terms-conditions': typeof PbAdminTermsConditionsRoute
  '/pb-admin/views-report': typeof PbAdminViewsReportRoute
  '/publisher/bank-accounts': typeof PublisherBankAccountsRoute
  '/publisher/margin-report': typeof PublisherMarginReportRoute
  '/publisher/profile': typeof PublisherProfileRoute
  '/publisher/sales-report': typeof PublisherSalesReportRoute
  '/publisher/settings': typeof PublisherSettingsRoute
  '/publisher/support': typeof PublisherSupportRoute
  '/author/': typeof AuthorIndexRoute
  '/library-admin/': typeof LibraryAdminIndexRoute
  '/pb-admin-lib/': typeof PbAdminLibIndexRoute
  '/pb-admin/': typeof PbAdminIndexRoute
  '/publisher/': typeof PublisherIndexRoute
  '/pb-admin-lib/libraries/$id': typeof PbAdminLibLibrariesIdRoute
  '/pb-admin-lib/libraries/new': typeof PbAdminLibLibrariesNewRoute
  '/pb-admin-lib/orders/$id': typeof PbAdminLibOrdersIdRoute
  '/pb-admin-lib/privacy-policy/$id': typeof PbAdminLibPrivacyPolicyIdRoute
  '/pb-admin-lib/privacy-policy/new': typeof PbAdminLibPrivacyPolicyNewRoute
  '/pb-admin-lib/terms-conditions/$id': typeof PbAdminLibTermsConditionsIdRoute
  '/pb-admin-lib/terms-conditions/new': typeof PbAdminLibTermsConditionsNewRoute
  '/pb-admin/ad-banners/image': typeof PbAdminAdBannersImageRoute
  '/pb-admin/ad-banners/popup': typeof PbAdminAdBannersPopupRoute
  '/pb-admin/author-management/$authorId': typeof PbAdminAuthorManagementAuthorIdRoute
  '/pb-admin/bundles/$bundleId': typeof PbAdminBundlesBundleIdRoute
  '/pb-admin/bundles/new': typeof PbAdminBundlesNewRoute
  '/pb-admin/commission-rates/$id': typeof PbAdminCommissionRatesIdRoute
  '/pb-admin/marketing/schema-meta': typeof PbAdminMarketingSchemaMetaRoute
  '/pb-admin/marketing/sitemap': typeof PbAdminMarketingSitemapRoute
  '/pb-admin/privacy-policy/$id': typeof PbAdminPrivacyPolicyIdRoute
  '/pb-admin/privacy-policy/new': typeof PbAdminPrivacyPolicyNewRoute
  '/pb-admin/publishers-authors/$id': typeof PbAdminPublishersAuthorsIdRouteWithChildren
  '/pb-admin/terms-conditions/$id': typeof PbAdminTermsConditionsIdRoute
  '/pb-admin/terms-conditions/new': typeof PbAdminTermsConditionsNewRoute
  '/pb-admin/titles/$bookId': typeof PbAdminTitlesBookIdRoute
  '/pb-admin/titles/new': typeof PbAdminTitlesNewRoute
  '/publisher/bundles/$bundleId': typeof PublisherBundlesBundleIdRoute
  '/publisher/bundles/new': typeof PublisherBundlesNewRoute
  '/publisher/catalogue-import/$fileName': typeof PublisherCatalogueImportFileNameRoute
  '/publisher/catalogue-import/new': typeof PublisherCatalogueImportNewRoute
  '/publisher/catalogue/$bookId': typeof PublisherCatalogueBookIdRoute
  '/publisher/catalogue/new': typeof PublisherCatalogueNewRoute
  '/publisher/promo-codes/$promoId': typeof PublisherPromoCodesPromoIdRoute
  '/publisher/promo-codes/new': typeof PublisherPromoCodesNewRoute
  '/pb-admin/bundles/': typeof PbAdminBundlesIndexRoute
  '/pb-admin/titles/': typeof PbAdminTitlesIndexRoute
  '/publisher/bundles/': typeof PublisherBundlesIndexRoute
  '/publisher/catalogue-import/': typeof PublisherCatalogueImportIndexRoute
  '/publisher/catalogue/': typeof PublisherCatalogueIndexRoute
  '/publisher/promo-codes/': typeof PublisherPromoCodesIndexRoute
  '/pb-admin/publishers-authors/$id/titles': typeof PbAdminPublishersAuthorsIdTitlesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library-user': typeof LibraryUserRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/author/profile': typeof AuthorProfileRoute
  '/library-admin/banners': typeof LibraryAdminBannersRoute
  '/library-admin/cart': typeof LibraryAdminCartRoute
  '/library-admin/catalogue': typeof LibraryAdminCatalogueRoute
  '/library-admin/courses': typeof LibraryAdminCoursesRoute
  '/library-admin/departments': typeof LibraryAdminDepartmentsRoute
  '/library-admin/manage-ebooks': typeof LibraryAdminManageEbooksRoute
  '/library-admin/orders': typeof LibraryAdminOrdersRoute
  '/library-admin/profile': typeof LibraryAdminProfileRoute
  '/library-admin/reports': typeof LibraryAdminReportsRoute
  '/library-admin/requests': typeof LibraryAdminRequestsRoute
  '/library-admin/support': typeof LibraryAdminSupportRoute
  '/library-admin/users': typeof LibraryAdminUsersRoute
  '/library-user/profile': typeof LibraryUserProfileRoute
  '/pb-admin-lib/catalogue': typeof PbAdminLibCatalogueRoute
  '/pb-admin-lib/clone': typeof PbAdminLibCloneRoute
  '/pb-admin-lib/libraries': typeof PbAdminLibLibrariesRoute
  '/pb-admin-lib/orders': typeof PbAdminLibOrdersRoute
  '/pb-admin-lib/privacy-policy': typeof PbAdminLibPrivacyPolicyRoute
  '/pb-admin-lib/reports': typeof PbAdminLibReportsRoute
  '/pb-admin-lib/settings': typeof PbAdminLibSettingsRoute
  '/pb-admin-lib/terms-conditions': typeof PbAdminLibTermsConditionsRoute
  '/pb-admin/admin-users': typeof PbAdminAdminUsersRoute
  '/pb-admin/audit-log': typeof PbAdminAuditLogRoute
  '/pb-admin/author-management': typeof PbAdminAuthorManagementRouteWithChildren
  '/pb-admin/cart-analysis': typeof PbAdminCartAnalysisRoute
  '/pb-admin/cart-view': typeof PbAdminCartViewRoute
  '/pb-admin/categories': typeof PbAdminCategoriesRoute
  '/pb-admin/commission-rates': typeof PbAdminCommissionRatesRoute
  '/pb-admin/customers': typeof PbAdminCustomersRoute
  '/pb-admin/featured-collections': typeof PbAdminFeaturedCollectionsRoute
  '/pb-admin/margin-report': typeof PbAdminMarginReportRoute
  '/pb-admin/merge-authors': typeof PbAdminMergeAuthorsRoute
  '/pb-admin/notifications': typeof PbAdminNotificationsRoute
  '/pb-admin/privacy-policy': typeof PbAdminPrivacyPolicyRoute
  '/pb-admin/profile': typeof PbAdminProfileRoute
  '/pb-admin/promo-codes': typeof PbAdminPromoCodesRoute
  '/pb-admin/publishers-authors': typeof PbAdminPublishersAuthorsRouteWithChildren
  '/pb-admin/quizz-rewards': typeof PbAdminQuizzRewardsRoute
  '/pb-admin/quizzes-rewards': typeof PbAdminQuizzesRewardsRoute
  '/pb-admin/sales-report': typeof PbAdminSalesReportRoute
  '/pb-admin/settings': typeof PbAdminSettingsRoute
  '/pb-admin/terms-conditions': typeof PbAdminTermsConditionsRoute
  '/pb-admin/views-report': typeof PbAdminViewsReportRoute
  '/publisher/bank-accounts': typeof PublisherBankAccountsRoute
  '/publisher/margin-report': typeof PublisherMarginReportRoute
  '/publisher/profile': typeof PublisherProfileRoute
  '/publisher/sales-report': typeof PublisherSalesReportRoute
  '/publisher/settings': typeof PublisherSettingsRoute
  '/publisher/support': typeof PublisherSupportRoute
  '/author': typeof AuthorIndexRoute
  '/library-admin': typeof LibraryAdminIndexRoute
  '/pb-admin-lib': typeof PbAdminLibIndexRoute
  '/pb-admin': typeof PbAdminIndexRoute
  '/publisher': typeof PublisherIndexRoute
  '/pb-admin-lib/libraries/$id': typeof PbAdminLibLibrariesIdRoute
  '/pb-admin-lib/libraries/new': typeof PbAdminLibLibrariesNewRoute
  '/pb-admin-lib/orders/$id': typeof PbAdminLibOrdersIdRoute
  '/pb-admin-lib/privacy-policy/$id': typeof PbAdminLibPrivacyPolicyIdRoute
  '/pb-admin-lib/privacy-policy/new': typeof PbAdminLibPrivacyPolicyNewRoute
  '/pb-admin-lib/terms-conditions/$id': typeof PbAdminLibTermsConditionsIdRoute
  '/pb-admin-lib/terms-conditions/new': typeof PbAdminLibTermsConditionsNewRoute
  '/pb-admin/ad-banners/image': typeof PbAdminAdBannersImageRoute
  '/pb-admin/ad-banners/popup': typeof PbAdminAdBannersPopupRoute
  '/pb-admin/author-management/$authorId': typeof PbAdminAuthorManagementAuthorIdRoute
  '/pb-admin/bundles/$bundleId': typeof PbAdminBundlesBundleIdRoute
  '/pb-admin/bundles/new': typeof PbAdminBundlesNewRoute
  '/pb-admin/commission-rates/$id': typeof PbAdminCommissionRatesIdRoute
  '/pb-admin/marketing/schema-meta': typeof PbAdminMarketingSchemaMetaRoute
  '/pb-admin/marketing/sitemap': typeof PbAdminMarketingSitemapRoute
  '/pb-admin/privacy-policy/$id': typeof PbAdminPrivacyPolicyIdRoute
  '/pb-admin/privacy-policy/new': typeof PbAdminPrivacyPolicyNewRoute
  '/pb-admin/publishers-authors/$id': typeof PbAdminPublishersAuthorsIdRouteWithChildren
  '/pb-admin/terms-conditions/$id': typeof PbAdminTermsConditionsIdRoute
  '/pb-admin/terms-conditions/new': typeof PbAdminTermsConditionsNewRoute
  '/pb-admin/titles/$bookId': typeof PbAdminTitlesBookIdRoute
  '/pb-admin/titles/new': typeof PbAdminTitlesNewRoute
  '/publisher/bundles/$bundleId': typeof PublisherBundlesBundleIdRoute
  '/publisher/bundles/new': typeof PublisherBundlesNewRoute
  '/publisher/catalogue-import/$fileName': typeof PublisherCatalogueImportFileNameRoute
  '/publisher/catalogue-import/new': typeof PublisherCatalogueImportNewRoute
  '/publisher/catalogue/$bookId': typeof PublisherCatalogueBookIdRoute
  '/publisher/catalogue/new': typeof PublisherCatalogueNewRoute
  '/publisher/promo-codes/$promoId': typeof PublisherPromoCodesPromoIdRoute
  '/publisher/promo-codes/new': typeof PublisherPromoCodesNewRoute
  '/pb-admin/bundles': typeof PbAdminBundlesIndexRoute
  '/pb-admin/titles': typeof PbAdminTitlesIndexRoute
  '/publisher/bundles': typeof PublisherBundlesIndexRoute
  '/publisher/catalogue-import': typeof PublisherCatalogueImportIndexRoute
  '/publisher/catalogue': typeof PublisherCatalogueIndexRoute
  '/publisher/promo-codes': typeof PublisherPromoCodesIndexRoute
  '/pb-admin/publishers-authors/$id/titles': typeof PbAdminPublishersAuthorsIdTitlesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library-user': typeof LibraryUserRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/author/profile': typeof AuthorProfileRoute
  '/library-admin/banners': typeof LibraryAdminBannersRoute
  '/library-admin/cart': typeof LibraryAdminCartRoute
  '/library-admin/catalogue': typeof LibraryAdminCatalogueRoute
  '/library-admin/courses': typeof LibraryAdminCoursesRoute
  '/library-admin/departments': typeof LibraryAdminDepartmentsRoute
  '/library-admin/manage-ebooks': typeof LibraryAdminManageEbooksRoute
  '/library-admin/orders': typeof LibraryAdminOrdersRoute
  '/library-admin/profile': typeof LibraryAdminProfileRoute
  '/library-admin/reports': typeof LibraryAdminReportsRoute
  '/library-admin/requests': typeof LibraryAdminRequestsRoute
  '/library-admin/support': typeof LibraryAdminSupportRoute
  '/library-admin/users': typeof LibraryAdminUsersRoute
  '/library-user/profile': typeof LibraryUserProfileRoute
  '/pb-admin-lib/catalogue': typeof PbAdminLibCatalogueRoute
  '/pb-admin-lib/clone': typeof PbAdminLibCloneRoute
  '/pb-admin-lib/libraries': typeof PbAdminLibLibrariesRoute
  '/pb-admin-lib/orders': typeof PbAdminLibOrdersRoute
  '/pb-admin-lib/privacy-policy': typeof PbAdminLibPrivacyPolicyRoute
  '/pb-admin-lib/reports': typeof PbAdminLibReportsRoute
  '/pb-admin-lib/settings': typeof PbAdminLibSettingsRoute
  '/pb-admin-lib/terms-conditions': typeof PbAdminLibTermsConditionsRoute
  '/pb-admin/admin-users': typeof PbAdminAdminUsersRoute
  '/pb-admin/audit-log': typeof PbAdminAuditLogRoute
  '/pb-admin/author-management': typeof PbAdminAuthorManagementRouteWithChildren
  '/pb-admin/cart-analysis': typeof PbAdminCartAnalysisRoute
  '/pb-admin/cart-view': typeof PbAdminCartViewRoute
  '/pb-admin/categories': typeof PbAdminCategoriesRoute
  '/pb-admin/commission-rates': typeof PbAdminCommissionRatesRoute
  '/pb-admin/customers': typeof PbAdminCustomersRoute
  '/pb-admin/featured-collections': typeof PbAdminFeaturedCollectionsRoute
  '/pb-admin/margin-report': typeof PbAdminMarginReportRoute
  '/pb-admin/merge-authors': typeof PbAdminMergeAuthorsRoute
  '/pb-admin/notifications': typeof PbAdminNotificationsRoute
  '/pb-admin/privacy-policy': typeof PbAdminPrivacyPolicyRoute
  '/pb-admin/profile': typeof PbAdminProfileRoute
  '/pb-admin/promo-codes': typeof PbAdminPromoCodesRoute
  '/pb-admin/publishers-authors': typeof PbAdminPublishersAuthorsRouteWithChildren
  '/pb-admin/quizz-rewards': typeof PbAdminQuizzRewardsRoute
  '/pb-admin/quizzes-rewards': typeof PbAdminQuizzesRewardsRoute
  '/pb-admin/sales-report': typeof PbAdminSalesReportRoute
  '/pb-admin/settings': typeof PbAdminSettingsRoute
  '/pb-admin/terms-conditions': typeof PbAdminTermsConditionsRoute
  '/pb-admin/views-report': typeof PbAdminViewsReportRoute
  '/publisher/bank-accounts': typeof PublisherBankAccountsRoute
  '/publisher/margin-report': typeof PublisherMarginReportRoute
  '/publisher/profile': typeof PublisherProfileRoute
  '/publisher/sales-report': typeof PublisherSalesReportRoute
  '/publisher/settings': typeof PublisherSettingsRoute
  '/publisher/support': typeof PublisherSupportRoute
  '/author/': typeof AuthorIndexRoute
  '/library-admin/': typeof LibraryAdminIndexRoute
  '/pb-admin-lib/': typeof PbAdminLibIndexRoute
  '/pb-admin/': typeof PbAdminIndexRoute
  '/publisher/': typeof PublisherIndexRoute
  '/pb-admin-lib/libraries_/$id': typeof PbAdminLibLibrariesIdRoute
  '/pb-admin-lib/libraries_/new': typeof PbAdminLibLibrariesNewRoute
  '/pb-admin-lib/orders_/$id': typeof PbAdminLibOrdersIdRoute
  '/pb-admin-lib/privacy-policy_/$id': typeof PbAdminLibPrivacyPolicyIdRoute
  '/pb-admin-lib/privacy-policy_/new': typeof PbAdminLibPrivacyPolicyNewRoute
  '/pb-admin-lib/terms-conditions_/$id': typeof PbAdminLibTermsConditionsIdRoute
  '/pb-admin-lib/terms-conditions_/new': typeof PbAdminLibTermsConditionsNewRoute
  '/pb-admin/ad-banners/image': typeof PbAdminAdBannersImageRoute
  '/pb-admin/ad-banners/popup': typeof PbAdminAdBannersPopupRoute
  '/pb-admin/author-management/$authorId': typeof PbAdminAuthorManagementAuthorIdRoute
  '/pb-admin/bundles/$bundleId': typeof PbAdminBundlesBundleIdRoute
  '/pb-admin/bundles/new': typeof PbAdminBundlesNewRoute
  '/pb-admin/commission-rates_/$id': typeof PbAdminCommissionRatesIdRoute
  '/pb-admin/marketing/schema-meta': typeof PbAdminMarketingSchemaMetaRoute
  '/pb-admin/marketing/sitemap': typeof PbAdminMarketingSitemapRoute
  '/pb-admin/privacy-policy_/$id': typeof PbAdminPrivacyPolicyIdRoute
  '/pb-admin/privacy-policy_/new': typeof PbAdminPrivacyPolicyNewRoute
  '/pb-admin/publishers-authors/$id': typeof PbAdminPublishersAuthorsIdRouteWithChildren
  '/pb-admin/terms-conditions_/$id': typeof PbAdminTermsConditionsIdRoute
  '/pb-admin/terms-conditions_/new': typeof PbAdminTermsConditionsNewRoute
  '/pb-admin/titles/$bookId': typeof PbAdminTitlesBookIdRoute
  '/pb-admin/titles/new': typeof PbAdminTitlesNewRoute
  '/publisher/bundles/$bundleId': typeof PublisherBundlesBundleIdRoute
  '/publisher/bundles/new': typeof PublisherBundlesNewRoute
  '/publisher/catalogue-import/$fileName': typeof PublisherCatalogueImportFileNameRoute
  '/publisher/catalogue-import/new': typeof PublisherCatalogueImportNewRoute
  '/publisher/catalogue/$bookId': typeof PublisherCatalogueBookIdRoute
  '/publisher/catalogue/new': typeof PublisherCatalogueNewRoute
  '/publisher/promo-codes/$promoId': typeof PublisherPromoCodesPromoIdRoute
  '/publisher/promo-codes/new': typeof PublisherPromoCodesNewRoute
  '/pb-admin/bundles/': typeof PbAdminBundlesIndexRoute
  '/pb-admin/titles/': typeof PbAdminTitlesIndexRoute
  '/publisher/bundles/': typeof PublisherBundlesIndexRoute
  '/publisher/catalogue-import/': typeof PublisherCatalogueImportIndexRoute
  '/publisher/catalogue/': typeof PublisherCatalogueIndexRoute
  '/publisher/promo-codes/': typeof PublisherPromoCodesIndexRoute
  '/pb-admin/publishers-authors/$id/titles': typeof PbAdminPublishersAuthorsIdTitlesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library-user'
    | '/notifications'
    | '/author/profile'
    | '/library-admin/banners'
    | '/library-admin/cart'
    | '/library-admin/catalogue'
    | '/library-admin/courses'
    | '/library-admin/departments'
    | '/library-admin/manage-ebooks'
    | '/library-admin/orders'
    | '/library-admin/profile'
    | '/library-admin/reports'
    | '/library-admin/requests'
    | '/library-admin/support'
    | '/library-admin/users'
    | '/library-user/profile'
    | '/pb-admin-lib/catalogue'
    | '/pb-admin-lib/clone'
    | '/pb-admin-lib/libraries'
    | '/pb-admin-lib/orders'
    | '/pb-admin-lib/privacy-policy'
    | '/pb-admin-lib/reports'
    | '/pb-admin-lib/settings'
    | '/pb-admin-lib/terms-conditions'
    | '/pb-admin/admin-users'
    | '/pb-admin/audit-log'
    | '/pb-admin/author-management'
    | '/pb-admin/cart-analysis'
    | '/pb-admin/cart-view'
    | '/pb-admin/categories'
    | '/pb-admin/commission-rates'
    | '/pb-admin/customers'
    | '/pb-admin/featured-collections'
    | '/pb-admin/margin-report'
    | '/pb-admin/merge-authors'
    | '/pb-admin/notifications'
    | '/pb-admin/privacy-policy'
    | '/pb-admin/profile'
    | '/pb-admin/promo-codes'
    | '/pb-admin/publishers-authors'
    | '/pb-admin/quizz-rewards'
    | '/pb-admin/quizzes-rewards'
    | '/pb-admin/sales-report'
    | '/pb-admin/settings'
    | '/pb-admin/terms-conditions'
    | '/pb-admin/views-report'
    | '/publisher/bank-accounts'
    | '/publisher/margin-report'
    | '/publisher/profile'
    | '/publisher/sales-report'
    | '/publisher/settings'
    | '/publisher/support'
    | '/author/'
    | '/library-admin/'
    | '/pb-admin-lib/'
    | '/pb-admin/'
    | '/publisher/'
    | '/pb-admin-lib/libraries/$id'
    | '/pb-admin-lib/libraries/new'
    | '/pb-admin-lib/orders/$id'
    | '/pb-admin-lib/privacy-policy/$id'
    | '/pb-admin-lib/privacy-policy/new'
    | '/pb-admin-lib/terms-conditions/$id'
    | '/pb-admin-lib/terms-conditions/new'
    | '/pb-admin/ad-banners/image'
    | '/pb-admin/ad-banners/popup'
    | '/pb-admin/author-management/$authorId'
    | '/pb-admin/bundles/$bundleId'
    | '/pb-admin/bundles/new'
    | '/pb-admin/commission-rates/$id'
    | '/pb-admin/marketing/schema-meta'
    | '/pb-admin/marketing/sitemap'
    | '/pb-admin/privacy-policy/$id'
    | '/pb-admin/privacy-policy/new'
    | '/pb-admin/publishers-authors/$id'
    | '/pb-admin/terms-conditions/$id'
    | '/pb-admin/terms-conditions/new'
    | '/pb-admin/titles/$bookId'
    | '/pb-admin/titles/new'
    | '/publisher/bundles/$bundleId'
    | '/publisher/bundles/new'
    | '/publisher/catalogue-import/$fileName'
    | '/publisher/catalogue-import/new'
    | '/publisher/catalogue/$bookId'
    | '/publisher/catalogue/new'
    | '/publisher/promo-codes/$promoId'
    | '/publisher/promo-codes/new'
    | '/pb-admin/bundles/'
    | '/pb-admin/titles/'
    | '/publisher/bundles/'
    | '/publisher/catalogue-import/'
    | '/publisher/catalogue/'
    | '/publisher/promo-codes/'
    | '/pb-admin/publishers-authors/$id/titles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/library-user'
    | '/notifications'
    | '/author/profile'
    | '/library-admin/banners'
    | '/library-admin/cart'
    | '/library-admin/catalogue'
    | '/library-admin/courses'
    | '/library-admin/departments'
    | '/library-admin/manage-ebooks'
    | '/library-admin/orders'
    | '/library-admin/profile'
    | '/library-admin/reports'
    | '/library-admin/requests'
    | '/library-admin/support'
    | '/library-admin/users'
    | '/library-user/profile'
    | '/pb-admin-lib/catalogue'
    | '/pb-admin-lib/clone'
    | '/pb-admin-lib/libraries'
    | '/pb-admin-lib/orders'
    | '/pb-admin-lib/privacy-policy'
    | '/pb-admin-lib/reports'
    | '/pb-admin-lib/settings'
    | '/pb-admin-lib/terms-conditions'
    | '/pb-admin/admin-users'
    | '/pb-admin/audit-log'
    | '/pb-admin/author-management'
    | '/pb-admin/cart-analysis'
    | '/pb-admin/cart-view'
    | '/pb-admin/categories'
    | '/pb-admin/commission-rates'
    | '/pb-admin/customers'
    | '/pb-admin/featured-collections'
    | '/pb-admin/margin-report'
    | '/pb-admin/merge-authors'
    | '/pb-admin/notifications'
    | '/pb-admin/privacy-policy'
    | '/pb-admin/profile'
    | '/pb-admin/promo-codes'
    | '/pb-admin/publishers-authors'
    | '/pb-admin/quizz-rewards'
    | '/pb-admin/quizzes-rewards'
    | '/pb-admin/sales-report'
    | '/pb-admin/settings'
    | '/pb-admin/terms-conditions'
    | '/pb-admin/views-report'
    | '/publisher/bank-accounts'
    | '/publisher/margin-report'
    | '/publisher/profile'
    | '/publisher/sales-report'
    | '/publisher/settings'
    | '/publisher/support'
    | '/author'
    | '/library-admin'
    | '/pb-admin-lib'
    | '/pb-admin'
    | '/publisher'
    | '/pb-admin-lib/libraries/$id'
    | '/pb-admin-lib/libraries/new'
    | '/pb-admin-lib/orders/$id'
    | '/pb-admin-lib/privacy-policy/$id'
    | '/pb-admin-lib/privacy-policy/new'
    | '/pb-admin-lib/terms-conditions/$id'
    | '/pb-admin-lib/terms-conditions/new'
    | '/pb-admin/ad-banners/image'
    | '/pb-admin/ad-banners/popup'
    | '/pb-admin/author-management/$authorId'
    | '/pb-admin/bundles/$bundleId'
    | '/pb-admin/bundles/new'
    | '/pb-admin/commission-rates/$id'
    | '/pb-admin/marketing/schema-meta'
    | '/pb-admin/marketing/sitemap'
    | '/pb-admin/privacy-policy/$id'
    | '/pb-admin/privacy-policy/new'
    | '/pb-admin/publishers-authors/$id'
    | '/pb-admin/terms-conditions/$id'
    | '/pb-admin/terms-conditions/new'
    | '/pb-admin/titles/$bookId'
    | '/pb-admin/titles/new'
    | '/publisher/bundles/$bundleId'
    | '/publisher/bundles/new'
    | '/publisher/catalogue-import/$fileName'
    | '/publisher/catalogue-import/new'
    | '/publisher/catalogue/$bookId'
    | '/publisher/catalogue/new'
    | '/publisher/promo-codes/$promoId'
    | '/publisher/promo-codes/new'
    | '/pb-admin/bundles'
    | '/pb-admin/titles'
    | '/publisher/bundles'
    | '/publisher/catalogue-import'
    | '/publisher/catalogue'
    | '/publisher/promo-codes'
    | '/pb-admin/publishers-authors/$id/titles'
  id:
    | '__root__'
    | '/'
    | '/library-user'
    | '/notifications'
    | '/author/profile'
    | '/library-admin/banners'
    | '/library-admin/cart'
    | '/library-admin/catalogue'
    | '/library-admin/courses'
    | '/library-admin/departments'
    | '/library-admin/manage-ebooks'
    | '/library-admin/orders'
    | '/library-admin/profile'
    | '/library-admin/reports'
    | '/library-admin/requests'
    | '/library-admin/support'
    | '/library-admin/users'
    | '/library-user/profile'
    | '/pb-admin-lib/catalogue'
    | '/pb-admin-lib/clone'
    | '/pb-admin-lib/libraries'
    | '/pb-admin-lib/orders'
    | '/pb-admin-lib/privacy-policy'
    | '/pb-admin-lib/reports'
    | '/pb-admin-lib/settings'
    | '/pb-admin-lib/terms-conditions'
    | '/pb-admin/admin-users'
    | '/pb-admin/audit-log'
    | '/pb-admin/author-management'
    | '/pb-admin/cart-analysis'
    | '/pb-admin/cart-view'
    | '/pb-admin/categories'
    | '/pb-admin/commission-rates'
    | '/pb-admin/customers'
    | '/pb-admin/featured-collections'
    | '/pb-admin/margin-report'
    | '/pb-admin/merge-authors'
    | '/pb-admin/notifications'
    | '/pb-admin/privacy-policy'
    | '/pb-admin/profile'
    | '/pb-admin/promo-codes'
    | '/pb-admin/publishers-authors'
    | '/pb-admin/quizz-rewards'
    | '/pb-admin/quizzes-rewards'
    | '/pb-admin/sales-report'
    | '/pb-admin/settings'
    | '/pb-admin/terms-conditions'
    | '/pb-admin/views-report'
    | '/publisher/bank-accounts'
    | '/publisher/margin-report'
    | '/publisher/profile'
    | '/publisher/sales-report'
    | '/publisher/settings'
    | '/publisher/support'
    | '/author/'
    | '/library-admin/'
    | '/pb-admin-lib/'
    | '/pb-admin/'
    | '/publisher/'
    | '/pb-admin-lib/libraries_/$id'
    | '/pb-admin-lib/libraries_/new'
    | '/pb-admin-lib/orders_/$id'
    | '/pb-admin-lib/privacy-policy_/$id'
    | '/pb-admin-lib/privacy-policy_/new'
    | '/pb-admin-lib/terms-conditions_/$id'
    | '/pb-admin-lib/terms-conditions_/new'
    | '/pb-admin/ad-banners/image'
    | '/pb-admin/ad-banners/popup'
    | '/pb-admin/author-management/$authorId'
    | '/pb-admin/bundles/$bundleId'
    | '/pb-admin/bundles/new'
    | '/pb-admin/commission-rates_/$id'
    | '/pb-admin/marketing/schema-meta'
    | '/pb-admin/marketing/sitemap'
    | '/pb-admin/privacy-policy_/$id'
    | '/pb-admin/privacy-policy_/new'
    | '/pb-admin/publishers-authors/$id'
    | '/pb-admin/terms-conditions_/$id'
    | '/pb-admin/terms-conditions_/new'
    | '/pb-admin/titles/$bookId'
    | '/pb-admin/titles/new'
    | '/publisher/bundles/$bundleId'
    | '/publisher/bundles/new'
    | '/publisher/catalogue-import/$fileName'
    | '/publisher/catalogue-import/new'
    | '/publisher/catalogue/$bookId'
    | '/publisher/catalogue/new'
    | '/publisher/promo-codes/$promoId'
    | '/publisher/promo-codes/new'
    | '/pb-admin/bundles/'
    | '/pb-admin/titles/'
    | '/publisher/bundles/'
    | '/publisher/catalogue-import/'
    | '/publisher/catalogue/'
    | '/publisher/promo-codes/'
    | '/pb-admin/publishers-authors/$id/titles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryUserRoute: typeof LibraryUserRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  AuthorProfileRoute: typeof AuthorProfileRoute
  LibraryAdminBannersRoute: typeof LibraryAdminBannersRoute
  LibraryAdminCartRoute: typeof LibraryAdminCartRoute
  LibraryAdminCatalogueRoute: typeof LibraryAdminCatalogueRoute
  LibraryAdminCoursesRoute: typeof LibraryAdminCoursesRoute
  LibraryAdminDepartmentsRoute: typeof LibraryAdminDepartmentsRoute
  LibraryAdminManageEbooksRoute: typeof LibraryAdminManageEbooksRoute
  LibraryAdminOrdersRoute: typeof LibraryAdminOrdersRoute
  LibraryAdminProfileRoute: typeof LibraryAdminProfileRoute
  LibraryAdminReportsRoute: typeof LibraryAdminReportsRoute
  LibraryAdminRequestsRoute: typeof LibraryAdminRequestsRoute
  LibraryAdminSupportRoute: typeof LibraryAdminSupportRoute
  LibraryAdminUsersRoute: typeof LibraryAdminUsersRoute
  PbAdminLibCatalogueRoute: typeof PbAdminLibCatalogueRoute
  PbAdminLibCloneRoute: typeof PbAdminLibCloneRoute
  PbAdminLibLibrariesRoute: typeof PbAdminLibLibrariesRoute
  PbAdminLibOrdersRoute: typeof PbAdminLibOrdersRoute
  PbAdminLibPrivacyPolicyRoute: typeof PbAdminLibPrivacyPolicyRoute
  PbAdminLibReportsRoute: typeof PbAdminLibReportsRoute
  PbAdminLibSettingsRoute: typeof PbAdminLibSettingsRoute
  PbAdminLibTermsConditionsRoute: typeof PbAdminLibTermsConditionsRoute
  PbAdminAdminUsersRoute: typeof PbAdminAdminUsersRoute
  PbAdminAuditLogRoute: typeof PbAdminAuditLogRoute
  PbAdminAuthorManagementRoute: typeof PbAdminAuthorManagementRouteWithChildren
  PbAdminCartAnalysisRoute: typeof PbAdminCartAnalysisRoute
  PbAdminCartViewRoute: typeof PbAdminCartViewRoute
  PbAdminCategoriesRoute: typeof PbAdminCategoriesRoute
  PbAdminCommissionRatesRoute: typeof PbAdminCommissionRatesRoute
  PbAdminCustomersRoute: typeof PbAdminCustomersRoute
  PbAdminFeaturedCollectionsRoute: typeof PbAdminFeaturedCollectionsRoute
  PbAdminMarginReportRoute: typeof PbAdminMarginReportRoute
  PbAdminMergeAuthorsRoute: typeof PbAdminMergeAuthorsRoute
  PbAdminNotificationsRoute: typeof PbAdminNotificationsRoute
  PbAdminPrivacyPolicyRoute: typeof PbAdminPrivacyPolicyRoute
  PbAdminProfileRoute: typeof PbAdminProfileRoute
  PbAdminPromoCodesRoute: typeof PbAdminPromoCodesRoute
  PbAdminPublishersAuthorsRoute: typeof PbAdminPublishersAuthorsRouteWithChildren
  PbAdminQuizzRewardsRoute: typeof PbAdminQuizzRewardsRoute
  PbAdminQuizzesRewardsRoute: typeof PbAdminQuizzesRewardsRoute
  PbAdminSalesReportRoute: typeof PbAdminSalesReportRoute
  PbAdminSettingsRoute: typeof PbAdminSettingsRoute
  PbAdminTermsConditionsRoute: typeof PbAdminTermsConditionsRoute
  PbAdminViewsReportRoute: typeof PbAdminViewsReportRoute
  PublisherBankAccountsRoute: typeof PublisherBankAccountsRoute
  PublisherMarginReportRoute: typeof PublisherMarginReportRoute
  PublisherProfileRoute: typeof PublisherProfileRoute
  PublisherSalesReportRoute: typeof PublisherSalesReportRoute
  PublisherSettingsRoute: typeof PublisherSettingsRoute
  PublisherSupportRoute: typeof PublisherSupportRoute
  AuthorIndexRoute: typeof AuthorIndexRoute
  LibraryAdminIndexRoute: typeof LibraryAdminIndexRoute
  PbAdminLibIndexRoute: typeof PbAdminLibIndexRoute
  PbAdminIndexRoute: typeof PbAdminIndexRoute
  PublisherIndexRoute: typeof PublisherIndexRoute
  PbAdminLibLibrariesIdRoute: typeof PbAdminLibLibrariesIdRoute
  PbAdminLibLibrariesNewRoute: typeof PbAdminLibLibrariesNewRoute
  PbAdminLibOrdersIdRoute: typeof PbAdminLibOrdersIdRoute
  PbAdminLibPrivacyPolicyIdRoute: typeof PbAdminLibPrivacyPolicyIdRoute
  PbAdminLibPrivacyPolicyNewRoute: typeof PbAdminLibPrivacyPolicyNewRoute
  PbAdminLibTermsConditionsIdRoute: typeof PbAdminLibTermsConditionsIdRoute
  PbAdminLibTermsConditionsNewRoute: typeof PbAdminLibTermsConditionsNewRoute
  PbAdminAdBannersImageRoute: typeof PbAdminAdBannersImageRoute
  PbAdminAdBannersPopupRoute: typeof PbAdminAdBannersPopupRoute
  PbAdminBundlesBundleIdRoute: typeof PbAdminBundlesBundleIdRoute
  PbAdminBundlesNewRoute: typeof PbAdminBundlesNewRoute
  PbAdminCommissionRatesIdRoute: typeof PbAdminCommissionRatesIdRoute
  PbAdminMarketingSchemaMetaRoute: typeof PbAdminMarketingSchemaMetaRoute
  PbAdminMarketingSitemapRoute: typeof PbAdminMarketingSitemapRoute
  PbAdminPrivacyPolicyIdRoute: typeof PbAdminPrivacyPolicyIdRoute
  PbAdminPrivacyPolicyNewRoute: typeof PbAdminPrivacyPolicyNewRoute
  PbAdminTermsConditionsIdRoute: typeof PbAdminTermsConditionsIdRoute
  PbAdminTermsConditionsNewRoute: typeof PbAdminTermsConditionsNewRoute
  PbAdminTitlesBookIdRoute: typeof PbAdminTitlesBookIdRoute
  PbAdminTitlesNewRoute: typeof PbAdminTitlesNewRoute
  PublisherBundlesBundleIdRoute: typeof PublisherBundlesBundleIdRoute
  PublisherBundlesNewRoute: typeof PublisherBundlesNewRoute
  PublisherCatalogueImportFileNameRoute: typeof PublisherCatalogueImportFileNameRoute
  PublisherCatalogueImportNewRoute: typeof PublisherCatalogueImportNewRoute
  PublisherCatalogueBookIdRoute: typeof PublisherCatalogueBookIdRoute
  PublisherCatalogueNewRoute: typeof PublisherCatalogueNewRoute
  PublisherPromoCodesPromoIdRoute: typeof PublisherPromoCodesPromoIdRoute
  PublisherPromoCodesNewRoute: typeof PublisherPromoCodesNewRoute
  PbAdminBundlesIndexRoute: typeof PbAdminBundlesIndexRoute
  PbAdminTitlesIndexRoute: typeof PbAdminTitlesIndexRoute
  PublisherBundlesIndexRoute: typeof PublisherBundlesIndexRoute
  PublisherCatalogueImportIndexRoute: typeof PublisherCatalogueImportIndexRoute
  PublisherCatalogueIndexRoute: typeof PublisherCatalogueIndexRoute
  PublisherPromoCodesIndexRoute: typeof PublisherPromoCodesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-user': {
      id: '/library-user'
      path: '/library-user'
      fullPath: '/library-user'
      preLoaderRoute: typeof LibraryUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/': {
      id: '/publisher/'
      path: '/publisher'
      fullPath: '/publisher/'
      preLoaderRoute: typeof PublisherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/': {
      id: '/pb-admin/'
      path: '/pb-admin'
      fullPath: '/pb-admin/'
      preLoaderRoute: typeof PbAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin-lib/': {
      id: '/pb-admin-lib/'
      path: '/pb-admin-lib'
      fullPath: '/pb-admin-lib/'
      preLoaderRoute: typeof PbAdminLibIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-admin/': {
      id: '/library-admin/'
      path: '/library-admin'
      fullPath: '/library-admin/'
      preLoaderRoute: typeof LibraryAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/': {
      id: '/author/'
      path: '/author'
      fullPath: '/author/'
      preLoaderRoute: typeof AuthorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/support': {
      id: '/publisher/support'
      path: '/publisher/support'
      fullPath: '/publisher/support'
      preLoaderRoute: typeof PublisherSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/settings': {
      id: '/publisher/settings'
      path: '/publisher/settings'
      fullPath: '/publisher/settings'
      preLoaderRoute: typeof PublisherSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/sales-report': {
      id: '/publisher/sales-report'
      path: '/publisher/sales-report'
      fullPath: '/publisher/sales-report'
      preLoaderRoute: typeof PublisherSalesReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/profile': {
      id: '/publisher/profile'
      path: '/publisher/profile'
      fullPath: '/publisher/profile'
      preLoaderRoute: typeof PublisherProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/margin-report': {
      id: '/publisher/margin-report'
      path: '/publisher/margin-report'
      fullPath: '/publisher/margin-report'
      preLoaderRoute: typeof PublisherMarginReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/bank-accounts': {
      id: '/publisher/bank-accounts'
      path: '/publisher/bank-accounts'
      fullPath: '/publisher/bank-accounts'
      preLoaderRoute: typeof PublisherBankAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/views-report': {
      id: '/pb-admin/views-report'
      path: '/pb-admin/views-report'
      fullPath: '/pb-admin/views-report'
      preLoaderRoute: typeof PbAdminViewsReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/terms-conditions': {
      id: '/pb-admin/terms-conditions'
      path: '/pb-admin/terms-conditions'
      fullPath: '/pb-admin/terms-conditions'
      preLoaderRoute: typeof PbAdminTermsConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/settings': {
      id: '/pb-admin/settings'
      path: '/pb-admin/settings'
      fullPath: '/pb-admin/settings'
      preLoaderRoute: typeof PbAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/sales-report': {
      id: '/pb-admin/sales-report'
      path: '/pb-admin/sales-report'
      fullPath: '/pb-admin/sales-report'
      preLoaderRoute: typeof PbAdminSalesReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/quizzes-rewards': {
      id: '/pb-admin/quizzes-rewards'
      path: '/pb-admin/quizzes-rewards'
      fullPath: '/pb-admin/quizzes-rewards'
      preLoaderRoute: typeof PbAdminQuizzesRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/quizz-rewards': {
      id: '/pb-admin/quizz-rewards'
      path: '/pb-admin/quizz-rewards'
      fullPath: '/pb-admin/quizz-rewards'
      preLoaderRoute: typeof PbAdminQuizzRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/publishers-authors': {
      id: '/pb-admin/publishers-authors'
      path: '/pb-admin/publishers-authors'
      fullPath: '/pb-admin/publishers-authors'
      preLoaderRoute: typeof PbAdminPublishersAuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/promo-codes': {
      id: '/pb-admin/promo-codes'
      path: '/pb-admin/promo-codes'
      fullPath: '/pb-admin/promo-codes'
      preLoaderRoute: typeof PbAdminPromoCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/profile': {
      id: '/pb-admin/profile'
      path: '/pb-admin/profile'
      fullPath: '/pb-admin/profile'
      preLoaderRoute: typeof PbAdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/privacy-policy': {
      id: '/pb-admin/privacy-policy'
      path: '/pb-admin/privacy-policy'
      fullPath: '/pb-admin/privacy-policy'
      preLoaderRoute: typeof PbAdminPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/notifications': {
      id: '/pb-admin/notifications'
      path: '/pb-admin/notifications'
      fullPath: '/pb-admin/notifications'
      preLoaderRoute: typeof PbAdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/merge-authors': {
      id: '/pb-admin/merge-authors'
      path: '/pb-admin/merge-authors'
      fullPath: '/pb-admin/merge-authors'
      preLoaderRoute: typeof PbAdminMergeAuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/margin-report': {
      id: '/pb-admin/margin-report'
      path: '/pb-admin/margin-report'
      fullPath: '/pb-admin/margin-report'
      preLoaderRoute: typeof PbAdminMarginReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/featured-collections': {
      id: '/pb-admin/featured-collections'
      path: '/pb-admin/featured-collections'
      fullPath: '/pb-admin/featured-collections'
      preLoaderRoute: typeof PbAdminFeaturedCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/customers': {
      id: '/pb-admin/customers'
      path: '/pb-admin/customers'
      fullPath: '/pb-admin/customers'
      preLoaderRoute: typeof PbAdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/commission-rates': {
      id: '/pb-admin/commission-rates'
      path: '/pb-admin/commission-rates'
      fullPath: '/pb-admin/commission-rates'
      preLoaderRoute: typeof PbAdminCommissionRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/categories': {
      id: '/pb-admin/categories'
      path: '/pb-admin/categories'
      fullPath: '/pb-admin/categories'
      preLoaderRoute: typeof PbAdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/cart-view': {
      id: '/pb-admin/cart-view'
      path: '/pb-admin/cart-view'
      fullPath: '/pb-admin/cart-view'
      preLoaderRoute: typeof PbAdminCartViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/cart-analysis': {
      id: '/pb-admin/cart-analysis'
      path: '/pb-admin/cart-analysis'
      fullPath: '/pb-admin/cart-analysis'
      preLoaderRoute: typeof PbAdminCartAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/author-management': {
      id: '/pb-admin/author-management'
      path: '/pb-admin/author-management'
      fullPath: '/pb-admin/author-management'
      preLoaderRoute: typeof PbAdminAuthorManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/audit-log': {
      id: '/pb-admin/audit-log'
      path: '/pb-admin/audit-log'
      fullPath: '/pb-admin/audit-log'
      preLoaderRoute: typeof PbAdminAuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/admin-users': {
      id: '/pb-admin/admin-users'
      path: '/pb-admin/admin-users'
      fullPath: '/pb-admin/admin-users'
      preLoaderRoute: typeof PbAdminAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin-lib/terms-conditions': {
      id: '/pb-admin-lib/terms-conditions'
      path: '/pb-admin-lib/terms-conditions'
      fullPath: '/pb-admin-lib/terms-conditions'
      preLoaderRoute: typeof PbAdminLibTermsConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin-lib/settings': {
      id: '/pb-admin-lib/settings'
      path: '/pb-admin-lib/settings'
      fullPath: '/pb-admin-lib/settings'
      preLoaderRoute: typeof PbAdminLibSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin-lib/reports': {
      id: '/pb-admin-lib/reports'
      path: '/pb-admin-lib/reports'
      fullPath: '/pb-admin-lib/reports'
      preLoaderRoute: typeof PbAdminLibReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin-lib/privacy-policy': {
      id: '/pb-admin-lib/privacy-policy'
      path: '/pb-admin-lib/privacy-policy'
      fullPath: '/pb-admin-lib/privacy-policy'
      preLoaderRoute: typeof PbAdminLibPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin-lib/orders': {
      id: '/pb-admin-lib/orders'
      path: '/pb-admin-lib/orders'
      fullPath: '/pb-admin-lib/orders'
      preLoaderRoute: typeof PbAdminLibOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin-lib/libraries': {
      id: '/pb-admin-lib/libraries'
      path: '/pb-admin-lib/libraries'
      fullPath: '/pb-admin-lib/libraries'
      preLoaderRoute: typeof PbAdminLibLibrariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin-lib/clone': {
      id: '/pb-admin-lib/clone'
      path: '/pb-admin-lib/clone'
      fullPath: '/pb-admin-lib/clone'
      preLoaderRoute: typeof PbAdminLibCloneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin-lib/catalogue': {
      id: '/pb-admin-lib/catalogue'
      path: '/pb-admin-lib/catalogue'
      fullPath: '/pb-admin-lib/catalogue'
      preLoaderRoute: typeof PbAdminLibCatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-user/profile': {
      id: '/library-user/profile'
      path: '/profile'
      fullPath: '/library-user/profile'
      preLoaderRoute: typeof LibraryUserProfileRouteImport
      parentRoute: typeof LibraryUserRoute
    }
    '/library-admin/users': {
      id: '/library-admin/users'
      path: '/library-admin/users'
      fullPath: '/library-admin/users'
      preLoaderRoute: typeof LibraryAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-admin/support': {
      id: '/library-admin/support'
      path: '/library-admin/support'
      fullPath: '/library-admin/support'
      preLoaderRoute: typeof LibraryAdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-admin/requests': {
      id: '/library-admin/requests'
      path: '/library-admin/requests'
      fullPath: '/library-admin/requests'
      preLoaderRoute: typeof LibraryAdminRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-admin/reports': {
      id: '/library-admin/reports'
      path: '/library-admin/reports'
      fullPath: '/library-admin/reports'
      preLoaderRoute: typeof LibraryAdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-admin/profile': {
      id: '/library-admin/profile'
      path: '/library-admin/profile'
      fullPath: '/library-admin/profile'
      preLoaderRoute: typeof LibraryAdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-admin/orders': {
      id: '/library-admin/orders'
      path: '/library-admin/orders'
      fullPath: '/library-admin/orders'
      preLoaderRoute: typeof LibraryAdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-admin/manage-ebooks': {
      id: '/library-admin/manage-ebooks'
      path: '/library-admin/manage-ebooks'
      fullPath: '/library-admin/manage-ebooks'
      preLoaderRoute: typeof LibraryAdminManageEbooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-admin/departments': {
      id: '/library-admin/departments'
      path: '/library-admin/departments'
      fullPath: '/library-admin/departments'
      preLoaderRoute: typeof LibraryAdminDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-admin/courses': {
      id: '/library-admin/courses'
      path: '/library-admin/courses'
      fullPath: '/library-admin/courses'
      preLoaderRoute: typeof LibraryAdminCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-admin/catalogue': {
      id: '/library-admin/catalogue'
      path: '/library-admin/catalogue'
      fullPath: '/library-admin/catalogue'
      preLoaderRoute: typeof LibraryAdminCatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-admin/cart': {
      id: '/library-admin/cart'
      path: '/library-admin/cart'
      fullPath: '/library-admin/cart'
      preLoaderRoute: typeof LibraryAdminCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-admin/banners': {
      id: '/library-admin/banners'
      path: '/library-admin/banners'
      fullPath: '/library-admin/banners'
      preLoaderRoute: typeof LibraryAdminBannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/profile': {
      id: '/author/profile'
      path: '/author/profile'
      fullPath: '/author/profile'
      preLoaderRoute: typeof AuthorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/promo-codes/': {
      id: '/publisher/promo-codes/'
      path: '/publisher/promo-codes'
      fullPath: '/publisher/promo-codes/'
      preLoaderRoute: typeof PublisherPromoCodesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/catalogue/': {
      id: '/publisher/catalogue/'
      path: '/publisher/catalogue'
      fullPath: '/publisher/catalogue/'
      preLoaderRoute: typeof PublisherCatalogueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/catalogue-import/': {
      id: '/publisher/catalogue-import/'
      path: '/publisher/catalogue-import'
      fullPath: '/publisher/catalogue-import/'
      preLoaderRoute: typeof PublisherCatalogueImportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/bundles/': {
      id: '/publisher/bundles/'
      path: '/publisher/bundles'
      fullPath: '/publisher/bundles/'
      preLoaderRoute: typeof PublisherBundlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/titles/': {
      id: '/pb-admin/titles/'
      path: '/pb-admin/titles'
      fullPath: '/pb-admin/titles/'
      preLoaderRoute: typeof PbAdminTitlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/bundles/': {
      id: '/pb-admin/bundles/'
      path: '/pb-admin/bundles'
      fullPath: '/pb-admin/bundles/'
      preLoaderRoute: typeof PbAdminBundlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/promo-codes/new': {
      id: '/publisher/promo-codes/new'
      path: '/publisher/promo-codes/new'
      fullPath: '/publisher/promo-codes/new'
      preLoaderRoute: typeof PublisherPromoCodesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/promo-codes/$promoId': {
      id: '/publisher/promo-codes/$promoId'
      path: '/publisher/promo-codes/$promoId'
      fullPath: '/publisher/promo-codes/$promoId'
      preLoaderRoute: typeof PublisherPromoCodesPromoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/catalogue/new': {
      id: '/publisher/catalogue/new'
      path: '/publisher/catalogue/new'
      fullPath: '/publisher/catalogue/new'
      preLoaderRoute: typeof PublisherCatalogueNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/catalogue/$bookId': {
      id: '/publisher/catalogue/$bookId'
      path: '/publisher/catalogue/$bookId'
      fullPath: '/publisher/catalogue/$bookId'
      preLoaderRoute: typeof PublisherCatalogueBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/catalogue-import/new': {
      id: '/publisher/catalogue-import/new'
      path: '/publisher/catalogue-import/new'
      fullPath: '/publisher/catalogue-import/new'
      preLoaderRoute: typeof PublisherCatalogueImportNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/catalogue-import/$fileName': {
      id: '/publisher/catalogue-import/$fileName'
      path: '/publisher/catalogue-import/$fileName'
      fullPath: '/publisher/catalogue-import/$fileName'
      preLoaderRoute: typeof PublisherCatalogueImportFileNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/bundles/new': {
      id: '/publisher/bundles/new'
      path: '/publisher/bundles/new'
      fullPath: '/publisher/bundles/new'
      preLoaderRoute: typeof PublisherBundlesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/bundles/$bundleId': {
      id: '/publisher/bundles/$bundleId'
      path: '/publisher/bundles/$bundleId'
      fullPath: '/publisher/bundles/$bundleId'
      preLoaderRoute: typeof PublisherBundlesBundleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/titles/new': {
      id: '/pb-admin/titles/new'
      path: '/pb-admin/titles/new'
      fullPath: '/pb-admin/titles/new'
      preLoaderRoute: typeof PbAdminTitlesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/titles/$bookId': {
      id: '/pb-admin/titles/$bookId'
      path: '/pb-admin/titles/$bookId'
      fullPath: '/pb-admin/titles/$bookId'
      preLoaderRoute: typeof PbAdminTitlesBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/terms-conditions_/new': {
      id: '/pb-admin/terms-conditions_/new'
      path: '/pb-admin/terms-conditions/new'
      fullPath: '/pb-admin/terms-conditions/new'
      preLoaderRoute: typeof PbAdminTermsConditionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/terms-conditions_/$id': {
      id: '/pb-admin/terms-conditions_/$id'
      path: '/pb-admin/terms-conditions/$id'
      fullPath: '/pb-admin/terms-conditions/$id'
      preLoaderRoute: typeof PbAdminTermsConditionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/publishers-authors/$id': {
      id: '/pb-admin/publishers-authors/$id'
      path: '/$id'
      fullPath: '/pb-admin/publishers-authors/$id'
      preLoaderRoute: typeof PbAdminPublishersAuthorsIdRouteImport
      parentRoute: typeof PbAdminPublishersAuthorsRoute
    }
    '/pb-admin/privacy-policy_/new': {
      id: '/pb-admin/privacy-policy_/new'
      path: '/pb-admin/privacy-policy/new'
      fullPath: '/pb-admin/privacy-policy/new'
      preLoaderRoute: typeof PbAdminPrivacyPolicyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/privacy-policy_/$id': {
      id: '/pb-admin/privacy-policy_/$id'
      path: '/pb-admin/privacy-policy/$id'
      fullPath: '/pb-admin/privacy-policy/$id'
      preLoaderRoute: typeof PbAdminPrivacyPolicyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/marketing/sitemap': {
      id: '/pb-admin/marketing/sitemap'
      path: '/pb-admin/marketing/sitemap'
      fullPath: '/pb-admin/marketing/sitemap'
      preLoaderRoute: typeof PbAdminMarketingSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/marketing/schema-meta': {
      id: '/pb-admin/marketing/schema-meta'
      path: '/pb-admin/marketing/schema-meta'
      fullPath: '/pb-admin/marketing/schema-meta'
      preLoaderRoute: typeof PbAdminMarketingSchemaMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/commission-rates_/$id': {
      id: '/pb-admin/commission-rates_/$id'
      path: '/pb-admin/commission-rates/$id'
      fullPath: '/pb-admin/commission-rates/$id'
      preLoaderRoute: typeof PbAdminCommissionRatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/bundles/new': {
      id: '/pb-admin/bundles/new'
      path: '/pb-admin/bundles/new'
      fullPath: '/pb-admin/bundles/new'
      preLoaderRoute: typeof PbAdminBundlesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/bundles/$bundleId': {
      id: '/pb-admin/bundles/$bundleId'
      path: '/pb-admin/bundles/$bundleId'
      fullPath: '/pb-admin/bundles/$bundleId'
      preLoaderRoute: typeof PbAdminBundlesBundleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/author-management/$authorId': {
      id: '/pb-admin/author-management/$authorId'
      path: '/$authorId'
      fullPath: '/pb-admin/author-management/$authorId'
      preLoaderRoute: typeof PbAdminAuthorManagementAuthorIdRouteImport
      parentRoute: typeof PbAdminAuthorManagementRoute
    }
    '/pb-admin/ad-banners/popup': {
      id: '/pb-admin/ad-banners/popup'
      path: '/pb-admin/ad-banners/popup'
      fullPath: '/pb-admin/ad-banners/popup'
      preLoaderRoute: typeof PbAdminAdBannersPopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/ad-banners/image': {
      id: '/pb-admin/ad-banners/image'
      path: '/pb-admin/ad-banners/image'
      fullPath: '/pb-admin/ad-banners/image'
      preLoaderRoute: typeof PbAdminAdBannersImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin-lib/terms-conditions_/new': {
      id: '/pb-admin-lib/terms-conditions_/new'
      path: '/pb-admin-lib/terms-conditions/new'
      fullPath: '/pb-admin-lib/terms-conditions/new'
      preLoaderRoute: typeof PbAdminLibTermsConditionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin-lib/terms-conditions_/$id': {
      id: '/pb-admin-lib/terms-conditions_/$id'
      path: '/pb-admin-lib/terms-conditions/$id'
      fullPath: '/pb-admin-lib/terms-conditions/$id'
      preLoaderRoute: typeof PbAdminLibTermsConditionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin-lib/privacy-policy_/new': {
      id: '/pb-admin-lib/privacy-policy_/new'
      path: '/pb-admin-lib/privacy-policy/new'
      fullPath: '/pb-admin-lib/privacy-policy/new'
      preLoaderRoute: typeof PbAdminLibPrivacyPolicyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin-lib/privacy-policy_/$id': {
      id: '/pb-admin-lib/privacy-policy_/$id'
      path: '/pb-admin-lib/privacy-policy/$id'
      fullPath: '/pb-admin-lib/privacy-policy/$id'
      preLoaderRoute: typeof PbAdminLibPrivacyPolicyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin-lib/orders_/$id': {
      id: '/pb-admin-lib/orders_/$id'
      path: '/pb-admin-lib/orders/$id'
      fullPath: '/pb-admin-lib/orders/$id'
      preLoaderRoute: typeof PbAdminLibOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin-lib/libraries_/new': {
      id: '/pb-admin-lib/libraries_/new'
      path: '/pb-admin-lib/libraries/new'
      fullPath: '/pb-admin-lib/libraries/new'
      preLoaderRoute: typeof PbAdminLibLibrariesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin-lib/libraries_/$id': {
      id: '/pb-admin-lib/libraries_/$id'
      path: '/pb-admin-lib/libraries/$id'
      fullPath: '/pb-admin-lib/libraries/$id'
      preLoaderRoute: typeof PbAdminLibLibrariesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pb-admin/publishers-authors/$id/titles': {
      id: '/pb-admin/publishers-authors/$id/titles'
      path: '/titles'
      fullPath: '/pb-admin/publishers-authors/$id/titles'
      preLoaderRoute: typeof PbAdminPublishersAuthorsIdTitlesRouteImport
      parentRoute: typeof PbAdminPublishersAuthorsIdRoute
    }
  }
}

interface LibraryUserRouteChildren {
  LibraryUserProfileRoute: typeof LibraryUserProfileRoute
}

const LibraryUserRouteChildren: LibraryUserRouteChildren = {
  LibraryUserProfileRoute: LibraryUserProfileRoute,
}

const LibraryUserRouteWithChildren = LibraryUserRoute._addFileChildren(
  LibraryUserRouteChildren,
)

interface PbAdminAuthorManagementRouteChildren {
  PbAdminAuthorManagementAuthorIdRoute: typeof PbAdminAuthorManagementAuthorIdRoute
}

const PbAdminAuthorManagementRouteChildren: PbAdminAuthorManagementRouteChildren =
  {
    PbAdminAuthorManagementAuthorIdRoute: PbAdminAuthorManagementAuthorIdRoute,
  }

const PbAdminAuthorManagementRouteWithChildren =
  PbAdminAuthorManagementRoute._addFileChildren(
    PbAdminAuthorManagementRouteChildren,
  )

interface PbAdminPublishersAuthorsIdRouteChildren {
  PbAdminPublishersAuthorsIdTitlesRoute: typeof PbAdminPublishersAuthorsIdTitlesRoute
}

const PbAdminPublishersAuthorsIdRouteChildren: PbAdminPublishersAuthorsIdRouteChildren =
  {
    PbAdminPublishersAuthorsIdTitlesRoute:
      PbAdminPublishersAuthorsIdTitlesRoute,
  }

const PbAdminPublishersAuthorsIdRouteWithChildren =
  PbAdminPublishersAuthorsIdRoute._addFileChildren(
    PbAdminPublishersAuthorsIdRouteChildren,
  )

interface PbAdminPublishersAuthorsRouteChildren {
  PbAdminPublishersAuthorsIdRoute: typeof PbAdminPublishersAuthorsIdRouteWithChildren
}

const PbAdminPublishersAuthorsRouteChildren: PbAdminPublishersAuthorsRouteChildren =
  {
    PbAdminPublishersAuthorsIdRoute:
      PbAdminPublishersAuthorsIdRouteWithChildren,
  }

const PbAdminPublishersAuthorsRouteWithChildren =
  PbAdminPublishersAuthorsRoute._addFileChildren(
    PbAdminPublishersAuthorsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryUserRoute: LibraryUserRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  AuthorProfileRoute: AuthorProfileRoute,
  LibraryAdminBannersRoute: LibraryAdminBannersRoute,
  LibraryAdminCartRoute: LibraryAdminCartRoute,
  LibraryAdminCatalogueRoute: LibraryAdminCatalogueRoute,
  LibraryAdminCoursesRoute: LibraryAdminCoursesRoute,
  LibraryAdminDepartmentsRoute: LibraryAdminDepartmentsRoute,
  LibraryAdminManageEbooksRoute: LibraryAdminManageEbooksRoute,
  LibraryAdminOrdersRoute: LibraryAdminOrdersRoute,
  LibraryAdminProfileRoute: LibraryAdminProfileRoute,
  LibraryAdminReportsRoute: LibraryAdminReportsRoute,
  LibraryAdminRequestsRoute: LibraryAdminRequestsRoute,
  LibraryAdminSupportRoute: LibraryAdminSupportRoute,
  LibraryAdminUsersRoute: LibraryAdminUsersRoute,
  PbAdminLibCatalogueRoute: PbAdminLibCatalogueRoute,
  PbAdminLibCloneRoute: PbAdminLibCloneRoute,
  PbAdminLibLibrariesRoute: PbAdminLibLibrariesRoute,
  PbAdminLibOrdersRoute: PbAdminLibOrdersRoute,
  PbAdminLibPrivacyPolicyRoute: PbAdminLibPrivacyPolicyRoute,
  PbAdminLibReportsRoute: PbAdminLibReportsRoute,
  PbAdminLibSettingsRoute: PbAdminLibSettingsRoute,
  PbAdminLibTermsConditionsRoute: PbAdminLibTermsConditionsRoute,
  PbAdminAdminUsersRoute: PbAdminAdminUsersRoute,
  PbAdminAuditLogRoute: PbAdminAuditLogRoute,
  PbAdminAuthorManagementRoute: PbAdminAuthorManagementRouteWithChildren,
  PbAdminCartAnalysisRoute: PbAdminCartAnalysisRoute,
  PbAdminCartViewRoute: PbAdminCartViewRoute,
  PbAdminCategoriesRoute: PbAdminCategoriesRoute,
  PbAdminCommissionRatesRoute: PbAdminCommissionRatesRoute,
  PbAdminCustomersRoute: PbAdminCustomersRoute,
  PbAdminFeaturedCollectionsRoute: PbAdminFeaturedCollectionsRoute,
  PbAdminMarginReportRoute: PbAdminMarginReportRoute,
  PbAdminMergeAuthorsRoute: PbAdminMergeAuthorsRoute,
  PbAdminNotificationsRoute: PbAdminNotificationsRoute,
  PbAdminPrivacyPolicyRoute: PbAdminPrivacyPolicyRoute,
  PbAdminProfileRoute: PbAdminProfileRoute,
  PbAdminPromoCodesRoute: PbAdminPromoCodesRoute,
  PbAdminPublishersAuthorsRoute: PbAdminPublishersAuthorsRouteWithChildren,
  PbAdminQuizzRewardsRoute: PbAdminQuizzRewardsRoute,
  PbAdminQuizzesRewardsRoute: PbAdminQuizzesRewardsRoute,
  PbAdminSalesReportRoute: PbAdminSalesReportRoute,
  PbAdminSettingsRoute: PbAdminSettingsRoute,
  PbAdminTermsConditionsRoute: PbAdminTermsConditionsRoute,
  PbAdminViewsReportRoute: PbAdminViewsReportRoute,
  PublisherBankAccountsRoute: PublisherBankAccountsRoute,
  PublisherMarginReportRoute: PublisherMarginReportRoute,
  PublisherProfileRoute: PublisherProfileRoute,
  PublisherSalesReportRoute: PublisherSalesReportRoute,
  PublisherSettingsRoute: PublisherSettingsRoute,
  PublisherSupportRoute: PublisherSupportRoute,
  AuthorIndexRoute: AuthorIndexRoute,
  LibraryAdminIndexRoute: LibraryAdminIndexRoute,
  PbAdminLibIndexRoute: PbAdminLibIndexRoute,
  PbAdminIndexRoute: PbAdminIndexRoute,
  PublisherIndexRoute: PublisherIndexRoute,
  PbAdminLibLibrariesIdRoute: PbAdminLibLibrariesIdRoute,
  PbAdminLibLibrariesNewRoute: PbAdminLibLibrariesNewRoute,
  PbAdminLibOrdersIdRoute: PbAdminLibOrdersIdRoute,
  PbAdminLibPrivacyPolicyIdRoute: PbAdminLibPrivacyPolicyIdRoute,
  PbAdminLibPrivacyPolicyNewRoute: PbAdminLibPrivacyPolicyNewRoute,
  PbAdminLibTermsConditionsIdRoute: PbAdminLibTermsConditionsIdRoute,
  PbAdminLibTermsConditionsNewRoute: PbAdminLibTermsConditionsNewRoute,
  PbAdminAdBannersImageRoute: PbAdminAdBannersImageRoute,
  PbAdminAdBannersPopupRoute: PbAdminAdBannersPopupRoute,
  PbAdminBundlesBundleIdRoute: PbAdminBundlesBundleIdRoute,
  PbAdminBundlesNewRoute: PbAdminBundlesNewRoute,
  PbAdminCommissionRatesIdRoute: PbAdminCommissionRatesIdRoute,
  PbAdminMarketingSchemaMetaRoute: PbAdminMarketingSchemaMetaRoute,
  PbAdminMarketingSitemapRoute: PbAdminMarketingSitemapRoute,
  PbAdminPrivacyPolicyIdRoute: PbAdminPrivacyPolicyIdRoute,
  PbAdminPrivacyPolicyNewRoute: PbAdminPrivacyPolicyNewRoute,
  PbAdminTermsConditionsIdRoute: PbAdminTermsConditionsIdRoute,
  PbAdminTermsConditionsNewRoute: PbAdminTermsConditionsNewRoute,
  PbAdminTitlesBookIdRoute: PbAdminTitlesBookIdRoute,
  PbAdminTitlesNewRoute: PbAdminTitlesNewRoute,
  PublisherBundlesBundleIdRoute: PublisherBundlesBundleIdRoute,
  PublisherBundlesNewRoute: PublisherBundlesNewRoute,
  PublisherCatalogueImportFileNameRoute: PublisherCatalogueImportFileNameRoute,
  PublisherCatalogueImportNewRoute: PublisherCatalogueImportNewRoute,
  PublisherCatalogueBookIdRoute: PublisherCatalogueBookIdRoute,
  PublisherCatalogueNewRoute: PublisherCatalogueNewRoute,
  PublisherPromoCodesPromoIdRoute: PublisherPromoCodesPromoIdRoute,
  PublisherPromoCodesNewRoute: PublisherPromoCodesNewRoute,
  PbAdminBundlesIndexRoute: PbAdminBundlesIndexRoute,
  PbAdminTitlesIndexRoute: PbAdminTitlesIndexRoute,
  PublisherBundlesIndexRoute: PublisherBundlesIndexRoute,
  PublisherCatalogueImportIndexRoute: PublisherCatalogueImportIndexRoute,
  PublisherCatalogueIndexRoute: PublisherCatalogueIndexRoute,
  PublisherPromoCodesIndexRoute: PublisherPromoCodesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
